/*
 * FalaAI API
 * Transcribe, diagnose and score calls with 3 simple endpoints.  **Endpoints:** - `POST /v1/audio/transcriptions` — Audio to text - `POST /v1/analyze/diagnostic` — Conversation analysis - `POST /v1/analyze/auditoriaRisco` — Compliance audit  **Complete flow (Python):** ```python import httpx  API = 'https://api01-falaai.action.tec.br' KEY = 'fai_xxx' HD = {'Authorization': f'Bearer {KEY}'}  # 1. Transcribe files = {'file': open('call.mp3', 'rb')} resp = httpx.post(f'{API}/v1/audio/transcriptions', headers=HD, files=files, data={'model': 'falaai-transcribe-1', 'language': 'pt'}) tr = resp.json() print(f'Text: {tr[\"text\"][:100]}...')  # 2. Diagnose resp = httpx.post(f'{API}/v1/analyze/diagnostic', headers=HD, json={'dialog': tr['dialog'], 'language': 'pt-BR', 'duration_seconds': tr['duration_seconds']}) diag = resp.json() print(f'Sentiment: {diag[\"analysis\"][\"sentiment\"][\"list_choice\"]}') print(f'Summary: {diag[\"analysis\"][\"dialogue_summary\"][\"explanation\"][:100]}...')  # 3. Audit resp = httpx.post(f'{API}/v1/analyze/auditoriaRisco', headers=HD, json={'dialogo': tr['dialog'], 'duration_seconds': tr['duration_seconds']}) audit = resp.json() print(f'Score: {audit[\"audit_score\"]} | Verdict: {audit[\"verdict\"]}') print(f'Detections: {audit[\"total_detections\"]} | Violations: {len(audit[\"violations\"])} | Positives: {len(audit[\"positives\"])}') ```  **Authentication:** All endpoints require an API Key in the `Authorization` header: `Bearer fai_xxx`  Get your API Key at [falaai.action.tec.br/api](https://falaai.action.tec.br/api)
 *
 * The version of the OpenAPI document: 1.21.47
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.falaai.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.math.BigDecimal;
import java.util.Arrays;
import org.openapitools.jackson.nullable.JsonNullable;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonNull;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import com.falaai.JSON;

/**
 * AuditoriaRiscoConversationScoresV2
 */
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.25.0")
public class AuditoriaRiscoConversationScoresV2 {
  public static final String SERIALIZED_NAME_CONSOLIDATED_SCORE = "consolidated_score";
  @SerializedName(SERIALIZED_NAME_CONSOLIDATED_SCORE)
  @jakarta.annotation.Nullable
  private BigDecimal consolidatedScore;

  public static final String SERIALIZED_NAME_VIOLATION_DENSITY_PER_MIN = "violation_density_per_min";
  @SerializedName(SERIALIZED_NAME_VIOLATION_DENSITY_PER_MIN)
  @jakarta.annotation.Nullable
  private BigDecimal violationDensityPerMin;

  public static final String SERIALIZED_NAME_SENTIMENT_TREND = "sentiment_trend";
  @SerializedName(SERIALIZED_NAME_SENTIMENT_TREND)
  @jakarta.annotation.Nullable
  private Object sentimentTrend = null;

  public static final String SERIALIZED_NAME_PCT_TURNS_WITH_VIOLATION = "pct_turns_with_violation";
  @SerializedName(SERIALIZED_NAME_PCT_TURNS_WITH_VIOLATION)
  @jakarta.annotation.Nullable
  private BigDecimal pctTurnsWithViolation;

  public static final String SERIALIZED_NAME_MOST_CRITICAL_TURN = "most_critical_turn";
  @SerializedName(SERIALIZED_NAME_MOST_CRITICAL_TURN)
  @jakarta.annotation.Nullable
  private Object mostCriticalTurn = null;

  public static final String SERIALIZED_NAME_POSITIVE_NEGATIVE_RATIO = "positive_negative_ratio";
  @SerializedName(SERIALIZED_NAME_POSITIVE_NEGATIVE_RATIO)
  @jakarta.annotation.Nullable
  private Object positiveNegativeRatio = null;

  public static final String SERIALIZED_NAME_GLOBAL_RISK_SEVERITY = "global_risk_severity";
  @SerializedName(SERIALIZED_NAME_GLOBAL_RISK_SEVERITY)
  @jakarta.annotation.Nullable
  private String globalRiskSeverity;

  public static final String SERIALIZED_NAME_GLOBAL_RISK_SEVERITY_LABEL = "global_risk_severity_label";
  @SerializedName(SERIALIZED_NAME_GLOBAL_RISK_SEVERITY_LABEL)
  @jakarta.annotation.Nullable
  private String globalRiskSeverityLabel;

  public static final String SERIALIZED_NAME_GLOBAL_RISK_SEVERITY_COLOR = "global_risk_severity_color";
  @SerializedName(SERIALIZED_NAME_GLOBAL_RISK_SEVERITY_COLOR)
  @jakarta.annotation.Nullable
  private String globalRiskSeverityColor;

  public static final String SERIALIZED_NAME_RISK_LIKELIHOOD_AVG = "risk_likelihood_avg";
  @SerializedName(SERIALIZED_NAME_RISK_LIKELIHOOD_AVG)
  @jakarta.annotation.Nullable
  private BigDecimal riskLikelihoodAvg;

  public static final String SERIALIZED_NAME_RISK_IMPACT_AVG = "risk_impact_avg";
  @SerializedName(SERIALIZED_NAME_RISK_IMPACT_AVG)
  @jakarta.annotation.Nullable
  private BigDecimal riskImpactAvg;

  public AuditoriaRiscoConversationScoresV2() {
  }

  public AuditoriaRiscoConversationScoresV2 consolidatedScore(@jakarta.annotation.Nullable BigDecimal consolidatedScore) {
    this.consolidatedScore = consolidatedScore;
    return this;
  }

  /**
   * Consolidated score
   * @return consolidatedScore
   */
  @jakarta.annotation.Nullable
  public BigDecimal getConsolidatedScore() {
    return consolidatedScore;
  }

  public void setConsolidatedScore(@jakarta.annotation.Nullable BigDecimal consolidatedScore) {
    this.consolidatedScore = consolidatedScore;
  }


  public AuditoriaRiscoConversationScoresV2 violationDensityPerMin(@jakarta.annotation.Nullable BigDecimal violationDensityPerMin) {
    this.violationDensityPerMin = violationDensityPerMin;
    return this;
  }

  /**
   * Violation density/min
   * @return violationDensityPerMin
   */
  @jakarta.annotation.Nullable
  public BigDecimal getViolationDensityPerMin() {
    return violationDensityPerMin;
  }

  public void setViolationDensityPerMin(@jakarta.annotation.Nullable BigDecimal violationDensityPerMin) {
    this.violationDensityPerMin = violationDensityPerMin;
  }


  public AuditoriaRiscoConversationScoresV2 sentimentTrend(@jakarta.annotation.Nullable Object sentimentTrend) {
    this.sentimentTrend = sentimentTrend;
    return this;
  }

  /**
   * Sentiment trend
   * @return sentimentTrend
   */
  @jakarta.annotation.Nullable
  public Object getSentimentTrend() {
    return sentimentTrend;
  }

  public void setSentimentTrend(@jakarta.annotation.Nullable Object sentimentTrend) {
    this.sentimentTrend = sentimentTrend;
  }


  public AuditoriaRiscoConversationScoresV2 pctTurnsWithViolation(@jakarta.annotation.Nullable BigDecimal pctTurnsWithViolation) {
    this.pctTurnsWithViolation = pctTurnsWithViolation;
    return this;
  }

  /**
   * % turns with violation
   * @return pctTurnsWithViolation
   */
  @jakarta.annotation.Nullable
  public BigDecimal getPctTurnsWithViolation() {
    return pctTurnsWithViolation;
  }

  public void setPctTurnsWithViolation(@jakarta.annotation.Nullable BigDecimal pctTurnsWithViolation) {
    this.pctTurnsWithViolation = pctTurnsWithViolation;
  }


  public AuditoriaRiscoConversationScoresV2 mostCriticalTurn(@jakarta.annotation.Nullable Object mostCriticalTurn) {
    this.mostCriticalTurn = mostCriticalTurn;
    return this;
  }

  /**
   * Most critical turn
   * @return mostCriticalTurn
   */
  @jakarta.annotation.Nullable
  public Object getMostCriticalTurn() {
    return mostCriticalTurn;
  }

  public void setMostCriticalTurn(@jakarta.annotation.Nullable Object mostCriticalTurn) {
    this.mostCriticalTurn = mostCriticalTurn;
  }


  public AuditoriaRiscoConversationScoresV2 positiveNegativeRatio(@jakarta.annotation.Nullable Object positiveNegativeRatio) {
    this.positiveNegativeRatio = positiveNegativeRatio;
    return this;
  }

  /**
   * Positive:negative ratio
   * @return positiveNegativeRatio
   */
  @jakarta.annotation.Nullable
  public Object getPositiveNegativeRatio() {
    return positiveNegativeRatio;
  }

  public void setPositiveNegativeRatio(@jakarta.annotation.Nullable Object positiveNegativeRatio) {
    this.positiveNegativeRatio = positiveNegativeRatio;
  }


  public AuditoriaRiscoConversationScoresV2 globalRiskSeverity(@jakarta.annotation.Nullable String globalRiskSeverity) {
    this.globalRiskSeverity = globalRiskSeverity;
    return this;
  }

  /**
   * Global risk severity code
   * @return globalRiskSeverity
   */
  @jakarta.annotation.Nullable
  public String getGlobalRiskSeverity() {
    return globalRiskSeverity;
  }

  public void setGlobalRiskSeverity(@jakarta.annotation.Nullable String globalRiskSeverity) {
    this.globalRiskSeverity = globalRiskSeverity;
  }


  public AuditoriaRiscoConversationScoresV2 globalRiskSeverityLabel(@jakarta.annotation.Nullable String globalRiskSeverityLabel) {
    this.globalRiskSeverityLabel = globalRiskSeverityLabel;
    return this;
  }

  /**
   * Global risk severity label
   * @return globalRiskSeverityLabel
   */
  @jakarta.annotation.Nullable
  public String getGlobalRiskSeverityLabel() {
    return globalRiskSeverityLabel;
  }

  public void setGlobalRiskSeverityLabel(@jakarta.annotation.Nullable String globalRiskSeverityLabel) {
    this.globalRiskSeverityLabel = globalRiskSeverityLabel;
  }


  public AuditoriaRiscoConversationScoresV2 globalRiskSeverityColor(@jakarta.annotation.Nullable String globalRiskSeverityColor) {
    this.globalRiskSeverityColor = globalRiskSeverityColor;
    return this;
  }

  /**
   * Global risk severity color
   * @return globalRiskSeverityColor
   */
  @jakarta.annotation.Nullable
  public String getGlobalRiskSeverityColor() {
    return globalRiskSeverityColor;
  }

  public void setGlobalRiskSeverityColor(@jakarta.annotation.Nullable String globalRiskSeverityColor) {
    this.globalRiskSeverityColor = globalRiskSeverityColor;
  }


  public AuditoriaRiscoConversationScoresV2 riskLikelihoodAvg(@jakarta.annotation.Nullable BigDecimal riskLikelihoodAvg) {
    this.riskLikelihoodAvg = riskLikelihoodAvg;
    return this;
  }

  /**
   * Risk likelihood avg
   * @return riskLikelihoodAvg
   */
  @jakarta.annotation.Nullable
  public BigDecimal getRiskLikelihoodAvg() {
    return riskLikelihoodAvg;
  }

  public void setRiskLikelihoodAvg(@jakarta.annotation.Nullable BigDecimal riskLikelihoodAvg) {
    this.riskLikelihoodAvg = riskLikelihoodAvg;
  }


  public AuditoriaRiscoConversationScoresV2 riskImpactAvg(@jakarta.annotation.Nullable BigDecimal riskImpactAvg) {
    this.riskImpactAvg = riskImpactAvg;
    return this;
  }

  /**
   * Risk impact avg
   * @return riskImpactAvg
   */
  @jakarta.annotation.Nullable
  public BigDecimal getRiskImpactAvg() {
    return riskImpactAvg;
  }

  public void setRiskImpactAvg(@jakarta.annotation.Nullable BigDecimal riskImpactAvg) {
    this.riskImpactAvg = riskImpactAvg;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AuditoriaRiscoConversationScoresV2 auditoriaRiscoConversationScoresV2 = (AuditoriaRiscoConversationScoresV2) o;
    return Objects.equals(this.consolidatedScore, auditoriaRiscoConversationScoresV2.consolidatedScore) &&
        Objects.equals(this.violationDensityPerMin, auditoriaRiscoConversationScoresV2.violationDensityPerMin) &&
        Objects.equals(this.sentimentTrend, auditoriaRiscoConversationScoresV2.sentimentTrend) &&
        Objects.equals(this.pctTurnsWithViolation, auditoriaRiscoConversationScoresV2.pctTurnsWithViolation) &&
        Objects.equals(this.mostCriticalTurn, auditoriaRiscoConversationScoresV2.mostCriticalTurn) &&
        Objects.equals(this.positiveNegativeRatio, auditoriaRiscoConversationScoresV2.positiveNegativeRatio) &&
        Objects.equals(this.globalRiskSeverity, auditoriaRiscoConversationScoresV2.globalRiskSeverity) &&
        Objects.equals(this.globalRiskSeverityLabel, auditoriaRiscoConversationScoresV2.globalRiskSeverityLabel) &&
        Objects.equals(this.globalRiskSeverityColor, auditoriaRiscoConversationScoresV2.globalRiskSeverityColor) &&
        Objects.equals(this.riskLikelihoodAvg, auditoriaRiscoConversationScoresV2.riskLikelihoodAvg) &&
        Objects.equals(this.riskImpactAvg, auditoriaRiscoConversationScoresV2.riskImpactAvg);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
  public int hashCode() {
    return Objects.hash(consolidatedScore, violationDensityPerMin, sentimentTrend, pctTurnsWithViolation, mostCriticalTurn, positiveNegativeRatio, globalRiskSeverity, globalRiskSeverityLabel, globalRiskSeverityColor, riskLikelihoodAvg, riskImpactAvg);
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AuditoriaRiscoConversationScoresV2 {\n");
    sb.append("    consolidatedScore: ").append(toIndentedString(consolidatedScore)).append("\n");
    sb.append("    violationDensityPerMin: ").append(toIndentedString(violationDensityPerMin)).append("\n");
    sb.append("    sentimentTrend: ").append(toIndentedString(sentimentTrend)).append("\n");
    sb.append("    pctTurnsWithViolation: ").append(toIndentedString(pctTurnsWithViolation)).append("\n");
    sb.append("    mostCriticalTurn: ").append(toIndentedString(mostCriticalTurn)).append("\n");
    sb.append("    positiveNegativeRatio: ").append(toIndentedString(positiveNegativeRatio)).append("\n");
    sb.append("    globalRiskSeverity: ").append(toIndentedString(globalRiskSeverity)).append("\n");
    sb.append("    globalRiskSeverityLabel: ").append(toIndentedString(globalRiskSeverityLabel)).append("\n");
    sb.append("    globalRiskSeverityColor: ").append(toIndentedString(globalRiskSeverityColor)).append("\n");
    sb.append("    riskLikelihoodAvg: ").append(toIndentedString(riskLikelihoodAvg)).append("\n");
    sb.append("    riskImpactAvg: ").append(toIndentedString(riskImpactAvg)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("consolidated_score", "violation_density_per_min", "sentiment_trend", "pct_turns_with_violation", "most_critical_turn", "positive_negative_ratio", "global_risk_severity", "global_risk_severity_label", "global_risk_severity_color", "risk_likelihood_avg", "risk_impact_avg"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(0);
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to AuditoriaRiscoConversationScoresV2
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!AuditoriaRiscoConversationScoresV2.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field(s) %s in AuditoriaRiscoConversationScoresV2 is not found in the empty JSON string", AuditoriaRiscoConversationScoresV2.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!AuditoriaRiscoConversationScoresV2.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The field `%s` in the JSON string is not defined in the `AuditoriaRiscoConversationScoresV2` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("global_risk_severity") != null && !jsonObj.get("global_risk_severity").isJsonNull()) && !jsonObj.get("global_risk_severity").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `global_risk_severity` to be a primitive type in the JSON string but got `%s`", jsonObj.get("global_risk_severity").toString()));
      }
      if ((jsonObj.get("global_risk_severity_label") != null && !jsonObj.get("global_risk_severity_label").isJsonNull()) && !jsonObj.get("global_risk_severity_label").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `global_risk_severity_label` to be a primitive type in the JSON string but got `%s`", jsonObj.get("global_risk_severity_label").toString()));
      }
      if ((jsonObj.get("global_risk_severity_color") != null && !jsonObj.get("global_risk_severity_color").isJsonNull()) && !jsonObj.get("global_risk_severity_color").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `global_risk_severity_color` to be a primitive type in the JSON string but got `%s`", jsonObj.get("global_risk_severity_color").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!AuditoriaRiscoConversationScoresV2.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'AuditoriaRiscoConversationScoresV2' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<AuditoriaRiscoConversationScoresV2> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(AuditoriaRiscoConversationScoresV2.class));

       return (TypeAdapter<T>) new TypeAdapter<AuditoriaRiscoConversationScoresV2>() {
           @Override
           public void write(JsonWriter out, AuditoriaRiscoConversationScoresV2 value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public AuditoriaRiscoConversationScoresV2 read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of AuditoriaRiscoConversationScoresV2 given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of AuditoriaRiscoConversationScoresV2
   * @throws IOException if the JSON string is invalid with respect to AuditoriaRiscoConversationScoresV2
   */
  public static AuditoriaRiscoConversationScoresV2 fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, AuditoriaRiscoConversationScoresV2.class);
  }

  /**
   * Convert an instance of AuditoriaRiscoConversationScoresV2 to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

