/*
 * FalaAI API
 * Transcribe, diagnose and score calls with 3 simple endpoints.  **Endpoints:** - `POST /v1/audio/transcriptions` — Audio to text - `POST /v1/analyze/diagnostic` — Conversation analysis - `POST /v1/analyze/auditoriaRisco` — Compliance audit  **Complete flow (Python):** ```python import httpx  API = 'https://api.fala.ai' KEY = 'fai_xxx' HD = {'Authorization': f'Bearer {KEY}'}  # 1. Transcribe files = {'file': open('call.mp3', 'rb')} resp = httpx.post(f'{API}/v1/audio/transcriptions', headers=HD, files=files, data={'model': 'falaai-transcribe-1', 'language': 'pt'}) tr = resp.json() print(f'Text: {tr[\"text\"][:100]}...')  # 2. Diagnose resp = httpx.post(f'{API}/v1/analyze/diagnostic', headers=HD, json={'dialog': tr['dialog'], 'language': 'pt-BR', 'duration_seconds': tr['duration_seconds']}) diag = resp.json() print(f'Sentiment: {diag[\"analysis\"][\"sentiment\"][\"list_choice\"]}') print(f'Summary: {diag[\"analysis\"][\"dialogue_summary\"][\"explanation\"][:100]}...')  # 3. Audit resp = httpx.post(f'{API}/v1/analyze/auditoriaRisco', headers=HD, json={'dialogo': tr['dialog'], 'duration_seconds': tr['duration_seconds']}) audit = resp.json() print(f'Score: {audit[\"audit_score\"]} | Verdict: {audit[\"verdict\"]}') print(f'Detections: {audit[\"total_detections\"]} | Violations: {len(audit[\"violations\"])} | Positives: {len(audit[\"positives\"])}') ```  **Authentication:** All endpoints require an API Key in the `Authorization` header: `Bearer fai_xxx`  Get your API Key at [falaai.action.tec.br/api](https://falaai.action.tec.br/api)
 *
 * The version of the OpenAPI document: 1.21.47
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.falaai.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.util.Map;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonNull;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import com.falaai.JSON;

/**
 * AuditoriaRiscoTimelineV2
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.25.0")
public class AuditoriaRiscoTimelineV2 {
  public static final String SERIALIZED_NAME_TURNS_SENTIMENT = "turns_sentiment";
  @SerializedName(SERIALIZED_NAME_TURNS_SENTIMENT)
  @javax.annotation.Nullable
  private List<Map<String, Object>> turnsSentiment = new ArrayList<>();

  public static final String SERIALIZED_NAME_AUDIO_EVENTS = "audio_events";
  @SerializedName(SERIALIZED_NAME_AUDIO_EVENTS)
  @javax.annotation.Nullable
  private List<Map<String, Object>> audioEvents = new ArrayList<>();

  public static final String SERIALIZED_NAME_AUDIO_GROUPS_FOUND = "audio_groups_found";
  @SerializedName(SERIALIZED_NAME_AUDIO_GROUPS_FOUND)
  @javax.annotation.Nullable
  private List<Map<String, Object>> audioGroupsFound = new ArrayList<>();

  public AuditoriaRiscoTimelineV2() {
  }

  public AuditoriaRiscoTimelineV2 turnsSentiment(@javax.annotation.Nullable List<Map<String, Object>> turnsSentiment) {
    this.turnsSentiment = turnsSentiment;
    return this;
  }

  public AuditoriaRiscoTimelineV2 addTurnsSentimentItem(Map<String, Object> turnsSentimentItem) {
    if (this.turnsSentiment == null) {
      this.turnsSentiment = new ArrayList<>();
    }
    this.turnsSentiment.add(turnsSentimentItem);
    return this;
  }

  /**
   * Per-turn sentiment
   * @return turnsSentiment
   */
  @javax.annotation.Nullable
  public List<Map<String, Object>> getTurnsSentiment() {
    return turnsSentiment;
  }

  public void setTurnsSentiment(@javax.annotation.Nullable List<Map<String, Object>> turnsSentiment) {
    this.turnsSentiment = turnsSentiment;
  }


  public AuditoriaRiscoTimelineV2 audioEvents(@javax.annotation.Nullable List<Map<String, Object>> audioEvents) {
    this.audioEvents = audioEvents;
    return this;
  }

  public AuditoriaRiscoTimelineV2 addAudioEventsItem(Map<String, Object> audioEventsItem) {
    if (this.audioEvents == null) {
      this.audioEvents = new ArrayList<>();
    }
    this.audioEvents.add(audioEventsItem);
    return this;
  }

  /**
   * Audio events (i18n)
   * @return audioEvents
   */
  @javax.annotation.Nullable
  public List<Map<String, Object>> getAudioEvents() {
    return audioEvents;
  }

  public void setAudioEvents(@javax.annotation.Nullable List<Map<String, Object>> audioEvents) {
    this.audioEvents = audioEvents;
  }


  public AuditoriaRiscoTimelineV2 audioGroupsFound(@javax.annotation.Nullable List<Map<String, Object>> audioGroupsFound) {
    this.audioGroupsFound = audioGroupsFound;
    return this;
  }

  public AuditoriaRiscoTimelineV2 addAudioGroupsFoundItem(Map<String, Object> audioGroupsFoundItem) {
    if (this.audioGroupsFound == null) {
      this.audioGroupsFound = new ArrayList<>();
    }
    this.audioGroupsFound.add(audioGroupsFoundItem);
    return this;
  }

  /**
   * Audio groups found
   * @return audioGroupsFound
   */
  @javax.annotation.Nullable
  public List<Map<String, Object>> getAudioGroupsFound() {
    return audioGroupsFound;
  }

  public void setAudioGroupsFound(@javax.annotation.Nullable List<Map<String, Object>> audioGroupsFound) {
    this.audioGroupsFound = audioGroupsFound;
  }

  /**
   * A container for additional, undeclared properties.
   * This is a holder for any undeclared properties as specified with
   * the 'additionalProperties' keyword in the OAS document.
   */
  private Map<String, Object> additionalProperties;

  /**
   * Set the additional (undeclared) property with the specified name and value.
   * If the property does not already exist, create it otherwise replace it.
   *
   * @param key name of the property
   * @param value value of the property
   * @return the AuditoriaRiscoTimelineV2 instance itself
   */
  public AuditoriaRiscoTimelineV2 putAdditionalProperty(String key, Object value) {
    if (this.additionalProperties == null) {
        this.additionalProperties = new HashMap<String, Object>();
    }
    this.additionalProperties.put(key, value);
    return this;
  }

  /**
   * Return the additional (undeclared) property.
   *
   * @return a map of objects
   */
  public Map<String, Object> getAdditionalProperties() {
    return additionalProperties;
  }

  /**
   * Return the additional (undeclared) property with the specified name.
   *
   * @param key name of the property
   * @return an object
   */
  public Object getAdditionalProperty(String key) {
    if (this.additionalProperties == null) {
        return null;
    }
    return this.additionalProperties.get(key);
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AuditoriaRiscoTimelineV2 auditoriaRiscoTimelineV2 = (AuditoriaRiscoTimelineV2) o;
    return Objects.equals(this.turnsSentiment, auditoriaRiscoTimelineV2.turnsSentiment) &&
        Objects.equals(this.audioEvents, auditoriaRiscoTimelineV2.audioEvents) &&
        Objects.equals(this.audioGroupsFound, auditoriaRiscoTimelineV2.audioGroupsFound)&&
        Objects.equals(this.additionalProperties, auditoriaRiscoTimelineV2.additionalProperties);
  }

  @Override
  public int hashCode() {
    return Objects.hash(turnsSentiment, audioEvents, audioGroupsFound, additionalProperties);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AuditoriaRiscoTimelineV2 {\n");
    sb.append("    turnsSentiment: ").append(toIndentedString(turnsSentiment)).append("\n");
    sb.append("    audioEvents: ").append(toIndentedString(audioEvents)).append("\n");
    sb.append("    audioGroupsFound: ").append(toIndentedString(audioGroupsFound)).append("\n");
    sb.append("    additionalProperties: ").append(toIndentedString(additionalProperties)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("turns_sentiment", "audio_events", "audio_groups_found"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(0);
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to AuditoriaRiscoTimelineV2
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!AuditoriaRiscoTimelineV2.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field(s) %s in AuditoriaRiscoTimelineV2 is not found in the empty JSON string", AuditoriaRiscoTimelineV2.openapiRequiredFields.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      // ensure the optional json data is an array if present
      if (jsonObj.get("turns_sentiment") != null && !jsonObj.get("turns_sentiment").isJsonNull() && !jsonObj.get("turns_sentiment").isJsonArray()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `turns_sentiment` to be an array in the JSON string but got `%s`", jsonObj.get("turns_sentiment").toString()));
      }
      // ensure the optional json data is an array if present
      if (jsonObj.get("audio_events") != null && !jsonObj.get("audio_events").isJsonNull() && !jsonObj.get("audio_events").isJsonArray()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `audio_events` to be an array in the JSON string but got `%s`", jsonObj.get("audio_events").toString()));
      }
      // ensure the optional json data is an array if present
      if (jsonObj.get("audio_groups_found") != null && !jsonObj.get("audio_groups_found").isJsonNull() && !jsonObj.get("audio_groups_found").isJsonArray()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `audio_groups_found` to be an array in the JSON string but got `%s`", jsonObj.get("audio_groups_found").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!AuditoriaRiscoTimelineV2.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'AuditoriaRiscoTimelineV2' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<AuditoriaRiscoTimelineV2> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(AuditoriaRiscoTimelineV2.class));

       return (TypeAdapter<T>) new TypeAdapter<AuditoriaRiscoTimelineV2>() {
           @Override
           public void write(JsonWriter out, AuditoriaRiscoTimelineV2 value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             obj.remove("additionalProperties");
             // serialize additional properties
             if (value.getAdditionalProperties() != null) {
               for (Map.Entry<String, Object> entry : value.getAdditionalProperties().entrySet()) {
                 if (entry.getValue() instanceof String)
                   obj.addProperty(entry.getKey(), (String) entry.getValue());
                 else if (entry.getValue() instanceof Number)
                   obj.addProperty(entry.getKey(), (Number) entry.getValue());
                 else if (entry.getValue() instanceof Boolean)
                   obj.addProperty(entry.getKey(), (Boolean) entry.getValue());
                 else if (entry.getValue() instanceof Character)
                   obj.addProperty(entry.getKey(), (Character) entry.getValue());
                 else {
                   JsonElement jsonElement = gson.toJsonTree(entry.getValue());
                   if (jsonElement.isJsonNull()) {
                     obj.add(entry.getKey(), JsonNull.INSTANCE);
                   } else if (jsonElement.isJsonArray()) {
                     obj.add(entry.getKey(), jsonElement.getAsJsonArray());
                   } else {
                     obj.add(entry.getKey(), jsonElement.getAsJsonObject());
                   }
                 }
               }
             }
             elementAdapter.write(out, obj);
           }

           @Override
           public AuditoriaRiscoTimelineV2 read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             JsonObject jsonObj = jsonElement.getAsJsonObject();
             // store additional fields in the deserialized instance
             AuditoriaRiscoTimelineV2 instance = thisAdapter.fromJsonTree(jsonObj);
             for (Map.Entry<String, JsonElement> entry : jsonObj.entrySet()) {
               if (!openapiFields.contains(entry.getKey())) {
                 if (entry.getValue().isJsonPrimitive()) { // primitive type
                   if (entry.getValue().getAsJsonPrimitive().isString())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsString());
                   else if (entry.getValue().getAsJsonPrimitive().isNumber())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsNumber());
                   else if (entry.getValue().getAsJsonPrimitive().isBoolean())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsBoolean());
                   else
                     throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The field `%s` has unknown primitive type. Value: %s", entry.getKey(), entry.getValue().toString()));
                 } else if (entry.getValue().isJsonArray()) {
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), List.class));
                 } else { // JSON object
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), HashMap.class));
                 }
               }
             }
             return instance;
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of AuditoriaRiscoTimelineV2 given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of AuditoriaRiscoTimelineV2
   * @throws IOException if the JSON string is invalid with respect to AuditoriaRiscoTimelineV2
   */
  public static AuditoriaRiscoTimelineV2 fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, AuditoriaRiscoTimelineV2.class);
  }

  /**
   * Convert an instance of AuditoriaRiscoTimelineV2 to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

