/*
 * FalaAI API
 * Transcribe, diagnose and score calls with 3 simple endpoints.  **Endpoints:** - `POST /v1/audio/transcriptions` — Audio to text - `POST /v1/analyze/diagnostic` — Conversation analysis - `POST /v1/analyze/auditoriaRisco` — Compliance audit  **Complete flow (Python):** ```python import httpx  API = 'https://api01-falaai.action.tec.br' KEY = 'fai_xxx' HD = {'Authorization': f'Bearer {KEY}'}  # 1. Transcribe files = {'file': open('call.mp3', 'rb')} resp = httpx.post(f'{API}/v1/audio/transcriptions', headers=HD, files=files, data={'model': 'falaai-transcribe-1', 'language': 'pt'}) tr = resp.json() print(f'Text: {tr[\"text\"][:100]}...')  # 2. Diagnose resp = httpx.post(f'{API}/v1/analyze/diagnostic', headers=HD, json={'dialog': tr['dialog'], 'language': 'pt-BR', 'duration_seconds': tr['duration_seconds']}) diag = resp.json() print(f'Sentiment: {diag[\"analysis\"][\"sentiment\"][\"list_choice\"]}') print(f'Summary: {diag[\"analysis\"][\"dialogue_summary\"][\"explanation\"][:100]}...')  # 3. Audit resp = httpx.post(f'{API}/v1/analyze/auditoriaRisco', headers=HD, json={'dialogo': tr['dialog'], 'duration_seconds': tr['duration_seconds']}) audit = resp.json() print(f'Score: {audit[\"audit_score\"]} | Verdict: {audit[\"verdict\"]}') print(f'Detections: {audit[\"total_detections\"]} | Violations: {len(audit[\"violations\"])} | Positives: {len(audit[\"positives\"])}') ```  **Authentication:** All endpoints require an API Key in the `Authorization` header: `Bearer fai_xxx`  Get your API Key at [falaai.action.tec.br/api](https://falaai.action.tec.br/api)
 *
 * The version of the OpenAPI document: 1.21.48
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.falaai.model;

import java.util.Objects;
import com.falaai.model.DiagnosticAudioEvent;
import com.falaai.model.Participant;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonNull;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import com.falaai.JSON;

/**
 * AuditoriaRiscoRequest
 */
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.25.0")
public class AuditoriaRiscoRequest {
  public static final String SERIALIZED_NAME_MODEL = "model";
  @SerializedName(SERIALIZED_NAME_MODEL)
  @jakarta.annotation.Nullable
  private String model = "falaai-auditoria-risco-1";

  public static final String SERIALIZED_NAME_TEXT = "text";
  @SerializedName(SERIALIZED_NAME_TEXT)
  @jakarta.annotation.Nullable
  private String text = "";

  public static final String SERIALIZED_NAME_DIALOG = "dialog";
  @SerializedName(SERIALIZED_NAME_DIALOG)
  @jakarta.annotation.Nullable
  private String dialog = "";

  public static final String SERIALIZED_NAME_AUDIO_EVENTS = "audio_events";
  @SerializedName(SERIALIZED_NAME_AUDIO_EVENTS)
  @jakarta.annotation.Nullable
  private List<DiagnosticAudioEvent> audioEvents = new ArrayList<>();

  public static final String SERIALIZED_NAME_DURATION_SECONDS = "duration_seconds";
  @SerializedName(SERIALIZED_NAME_DURATION_SECONDS)
  @jakarta.annotation.Nonnull
  private BigDecimal durationSeconds;

  public static final String SERIALIZED_NAME_LANGUAGE = "language";
  @SerializedName(SERIALIZED_NAME_LANGUAGE)
  @jakarta.annotation.Nonnull
  private String language;

  public static final String SERIALIZED_NAME_RESPONSE_LANGUAGE = "response_language";
  @SerializedName(SERIALIZED_NAME_RESPONSE_LANGUAGE)
  @jakarta.annotation.Nonnull
  private String responseLanguage;

  /**
   * Who originated the call. inbound&#x3D;client called, outbound&#x3D;company called. If omitted, LLM infers from context.
   */
  @JsonAdapter(CallDirectionEnum.Adapter.class)
  public enum CallDirectionEnum {
    INBOUND("inbound"),
    
    OUTBOUND("outbound");

    private String value;

    CallDirectionEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static CallDirectionEnum fromValue(String value) {
      for (CallDirectionEnum b : CallDirectionEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }

    public static class Adapter extends TypeAdapter<CallDirectionEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final CallDirectionEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public CallDirectionEnum read(final JsonReader jsonReader) throws IOException {
        String value =  jsonReader.nextString();
        return CallDirectionEnum.fromValue(value);
      }
    }

    public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      String value = jsonElement.getAsString();
      CallDirectionEnum.fromValue(value);
    }
  }

  public static final String SERIALIZED_NAME_CALL_DIRECTION = "call_direction";
  @SerializedName(SERIALIZED_NAME_CALL_DIRECTION)
  @jakarta.annotation.Nullable
  private CallDirectionEnum callDirection;

  public static final String SERIALIZED_NAME_PARTICIPANTS = "participants";
  @SerializedName(SERIALIZED_NAME_PARTICIPANTS)
  @jakarta.annotation.Nullable
  private List<Participant> participants = new ArrayList<>();

  public static final String SERIALIZED_NAME_RESPONSE_FORMAT = "response_format";
  @SerializedName(SERIALIZED_NAME_RESPONSE_FORMAT)
  @jakarta.annotation.Nullable
  private String responseFormat = "v2";

  public static final String SERIALIZED_NAME_CLIENT_REFERENCE_ID = "client_reference_id";
  @SerializedName(SERIALIZED_NAME_CLIENT_REFERENCE_ID)
  @jakarta.annotation.Nullable
  private String clientReferenceId;

  public AuditoriaRiscoRequest() {
  }

  public AuditoriaRiscoRequest model(@jakarta.annotation.Nullable String model) {
    this.model = model;
    return this;
  }

  /**
   * Analysis model. Always &#39;falaai-auditoria-risco-1&#39;
   * @return model
   */
  @jakarta.annotation.Nullable
  public String getModel() {
    return model;
  }

  public void setModel(@jakarta.annotation.Nullable String model) {
    this.model = model;
  }


  public AuditoriaRiscoRequest text(@jakarta.annotation.Nullable String text) {
    this.text = text;
    return this;
  }

  /**
   * Plain transcript (fallback if dialog is empty). At least one of &#39;dialog&#39; or &#39;text&#39; required. Max 300,000 characters
   * @return text
   */
  @jakarta.annotation.Nullable
  public String getText() {
    return text;
  }

  public void setText(@jakarta.annotation.Nullable String text) {
    this.text = text;
  }


  public AuditoriaRiscoRequest dialog(@jakarta.annotation.Nullable String dialog) {
    this.dialog = dialog;
    return this;
  }

  /**
   * Diarized transcript with speaker turns. PRIMARY source. Speaker labels accepted (any case): &#39;Speaker N&#39;, &#39;Interlocutor N&#39;, &#39;Hablante N&#39;, &#39;Locutor N&#39;, &#39;Orador N&#39; (space or underscore). Normalized internally to &#39;Speaker N&#39; in the response. Max 300,000 characters
   * @return dialog
   */
  @jakarta.annotation.Nullable
  public String getDialog() {
    return dialog;
  }

  public void setDialog(@jakarta.annotation.Nullable String dialog) {
    this.dialog = dialog;
  }


  public AuditoriaRiscoRequest audioEvents(@jakarta.annotation.Nullable List<DiagnosticAudioEvent> audioEvents) {
    this.audioEvents = audioEvents;
    return this;
  }

  public AuditoriaRiscoRequest addAudioEventsItem(DiagnosticAudioEvent audioEventsItem) {
    if (this.audioEvents == null) {
      this.audioEvents = new ArrayList<>();
    }
    this.audioEvents.add(audioEventsItem);
    return this;
  }

  /**
   * Audio events with timestamps (correlated with turns when diarization is present)
   * @return audioEvents
   */
  @jakarta.annotation.Nullable
  public List<DiagnosticAudioEvent> getAudioEvents() {
    return audioEvents;
  }

  public void setAudioEvents(@jakarta.annotation.Nullable List<DiagnosticAudioEvent> audioEvents) {
    this.audioEvents = audioEvents;
  }


  public AuditoriaRiscoRequest durationSeconds(@jakarta.annotation.Nonnull BigDecimal durationSeconds) {
    this.durationSeconds = durationSeconds;
    return this;
  }

  /**
   * Total audio duration in seconds. Required. Max 3h (10800s).
   * minimum: 1.0
   * @return durationSeconds
   */
  @jakarta.annotation.Nonnull
  public BigDecimal getDurationSeconds() {
    return durationSeconds;
  }

  public void setDurationSeconds(@jakarta.annotation.Nonnull BigDecimal durationSeconds) {
    this.durationSeconds = durationSeconds;
  }


  public AuditoriaRiscoRequest language(@jakarta.annotation.Nonnull String language) {
    this.language = language;
    return this;
  }

  /**
   * Language of the transcript being analyzed. Must match the dialog/text language. Accepted: pt-BR, en-US, es-ES.
   * @return language
   */
  @jakarta.annotation.Nonnull
  public String getLanguage() {
    return language;
  }

  public void setLanguage(@jakarta.annotation.Nonnull String language) {
    this.language = language;
  }


  public AuditoriaRiscoRequest responseLanguage(@jakarta.annotation.Nonnull String responseLanguage) {
    this.responseLanguage = responseLanguage;
    return this;
  }

  /**
   * Language for analysis results (labels, categories, levels, actions, HTML report). Can differ from &#39;language&#39;. Accepted: pt-BR, en-US, es-ES.
   * @return responseLanguage
   */
  @jakarta.annotation.Nonnull
  public String getResponseLanguage() {
    return responseLanguage;
  }

  public void setResponseLanguage(@jakarta.annotation.Nonnull String responseLanguage) {
    this.responseLanguage = responseLanguage;
  }


  public AuditoriaRiscoRequest callDirection(@jakarta.annotation.Nullable CallDirectionEnum callDirection) {
    this.callDirection = callDirection;
    return this;
  }

  /**
   * Who originated the call. inbound&#x3D;client called, outbound&#x3D;company called. If omitted, LLM infers from context.
   * @return callDirection
   */
  @jakarta.annotation.Nullable
  public CallDirectionEnum getCallDirection() {
    return callDirection;
  }

  public void setCallDirection(@jakarta.annotation.Nullable CallDirectionEnum callDirection) {
    this.callDirection = callDirection;
  }


  public AuditoriaRiscoRequest participants(@jakarta.annotation.Nullable List<Participant> participants) {
    this.participants = participants;
    return this;
  }

  public AuditoriaRiscoRequest addParticipantsItem(Participant participantsItem) {
    if (this.participants == null) {
      this.participants = new ArrayList<>();
    }
    this.participants.add(participantsItem);
    return this;
  }

  /**
   * Explicit participant roles. If omitted, LLM infers from dialog (Lei 17). When provided, used as ground truth â€” no inference.
   * @return participants
   */
  @jakarta.annotation.Nullable
  public List<Participant> getParticipants() {
    return participants;
  }

  public void setParticipants(@jakarta.annotation.Nullable List<Participant> participants) {
    this.participants = participants;
  }


  public AuditoriaRiscoRequest responseFormat(@jakarta.annotation.Nullable String responseFormat) {
    this.responseFormat = responseFormat;
    return this;
  }

  /**
   * Response format version. v1&#x3D;legacy flat PT-BR, v2&#x3D;structured EN-US blocks.
   * @return responseFormat
   */
  @jakarta.annotation.Nullable
  public String getResponseFormat() {
    return responseFormat;
  }

  public void setResponseFormat(@jakarta.annotation.Nullable String responseFormat) {
    this.responseFormat = responseFormat;
  }


  public AuditoriaRiscoRequest clientReferenceId(@jakarta.annotation.Nullable String clientReferenceId) {
    this.clientReferenceId = clientReferenceId;
    return this;
  }

  /**
   * Optional client-supplied ID echoed verbatim in the response. Use to correlate/sync with your system. Accepted charset: [A-Za-z0-9._:-], max 128 chars. Not idempotency.
   * @return clientReferenceId
   */
  @jakarta.annotation.Nullable
  public String getClientReferenceId() {
    return clientReferenceId;
  }

  public void setClientReferenceId(@jakarta.annotation.Nullable String clientReferenceId) {
    this.clientReferenceId = clientReferenceId;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AuditoriaRiscoRequest auditoriaRiscoRequest = (AuditoriaRiscoRequest) o;
    return Objects.equals(this.model, auditoriaRiscoRequest.model) &&
        Objects.equals(this.text, auditoriaRiscoRequest.text) &&
        Objects.equals(this.dialog, auditoriaRiscoRequest.dialog) &&
        Objects.equals(this.audioEvents, auditoriaRiscoRequest.audioEvents) &&
        Objects.equals(this.durationSeconds, auditoriaRiscoRequest.durationSeconds) &&
        Objects.equals(this.language, auditoriaRiscoRequest.language) &&
        Objects.equals(this.responseLanguage, auditoriaRiscoRequest.responseLanguage) &&
        Objects.equals(this.callDirection, auditoriaRiscoRequest.callDirection) &&
        Objects.equals(this.participants, auditoriaRiscoRequest.participants) &&
        Objects.equals(this.responseFormat, auditoriaRiscoRequest.responseFormat) &&
        Objects.equals(this.clientReferenceId, auditoriaRiscoRequest.clientReferenceId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(model, text, dialog, audioEvents, durationSeconds, language, responseLanguage, callDirection, participants, responseFormat, clientReferenceId);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AuditoriaRiscoRequest {\n");
    sb.append("    model: ").append(toIndentedString(model)).append("\n");
    sb.append("    text: ").append(toIndentedString(text)).append("\n");
    sb.append("    dialog: ").append(toIndentedString(dialog)).append("\n");
    sb.append("    audioEvents: ").append(toIndentedString(audioEvents)).append("\n");
    sb.append("    durationSeconds: ").append(toIndentedString(durationSeconds)).append("\n");
    sb.append("    language: ").append(toIndentedString(language)).append("\n");
    sb.append("    responseLanguage: ").append(toIndentedString(responseLanguage)).append("\n");
    sb.append("    callDirection: ").append(toIndentedString(callDirection)).append("\n");
    sb.append("    participants: ").append(toIndentedString(participants)).append("\n");
    sb.append("    responseFormat: ").append(toIndentedString(responseFormat)).append("\n");
    sb.append("    clientReferenceId: ").append(toIndentedString(clientReferenceId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("model", "text", "dialog", "audio_events", "duration_seconds", "language", "response_language", "call_direction", "participants", "response_format", "client_reference_id"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(Arrays.asList("duration_seconds", "language", "response_language"));
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to AuditoriaRiscoRequest
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!AuditoriaRiscoRequest.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field(s) %s in AuditoriaRiscoRequest is not found in the empty JSON string", AuditoriaRiscoRequest.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!AuditoriaRiscoRequest.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The field `%s` in the JSON string is not defined in the `AuditoriaRiscoRequest` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : AuditoriaRiscoRequest.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("model") != null && !jsonObj.get("model").isJsonNull()) && !jsonObj.get("model").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `model` to be a primitive type in the JSON string but got `%s`", jsonObj.get("model").toString()));
      }
      if ((jsonObj.get("text") != null && !jsonObj.get("text").isJsonNull()) && !jsonObj.get("text").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `text` to be a primitive type in the JSON string but got `%s`", jsonObj.get("text").toString()));
      }
      if ((jsonObj.get("dialog") != null && !jsonObj.get("dialog").isJsonNull()) && !jsonObj.get("dialog").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `dialog` to be a primitive type in the JSON string but got `%s`", jsonObj.get("dialog").toString()));
      }
      if (jsonObj.get("audio_events") != null && !jsonObj.get("audio_events").isJsonNull()) {
        JsonArray jsonArrayaudioEvents = jsonObj.getAsJsonArray("audio_events");
        if (jsonArrayaudioEvents != null) {
          // ensure the json data is an array
          if (!jsonObj.get("audio_events").isJsonArray()) {
            throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `audio_events` to be an array in the JSON string but got `%s`", jsonObj.get("audio_events").toString()));
          }

          // validate the optional field `audio_events` (array)
          for (int i = 0; i < jsonArrayaudioEvents.size(); i++) {
            DiagnosticAudioEvent.validateJsonElement(jsonArrayaudioEvents.get(i));
          };
        }
      }
      if (!jsonObj.get("language").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `language` to be a primitive type in the JSON string but got `%s`", jsonObj.get("language").toString()));
      }
      if (!jsonObj.get("response_language").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `response_language` to be a primitive type in the JSON string but got `%s`", jsonObj.get("response_language").toString()));
      }
      if ((jsonObj.get("call_direction") != null && !jsonObj.get("call_direction").isJsonNull()) && !jsonObj.get("call_direction").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `call_direction` to be a primitive type in the JSON string but got `%s`", jsonObj.get("call_direction").toString()));
      }
      // validate the optional field `call_direction`
      if (jsonObj.get("call_direction") != null && !jsonObj.get("call_direction").isJsonNull()) {
        CallDirectionEnum.validateJsonElement(jsonObj.get("call_direction"));
      }
      if (jsonObj.get("participants") != null && !jsonObj.get("participants").isJsonNull()) {
        JsonArray jsonArrayparticipants = jsonObj.getAsJsonArray("participants");
        if (jsonArrayparticipants != null) {
          // ensure the json data is an array
          if (!jsonObj.get("participants").isJsonArray()) {
            throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `participants` to be an array in the JSON string but got `%s`", jsonObj.get("participants").toString()));
          }

          // validate the optional field `participants` (array)
          for (int i = 0; i < jsonArrayparticipants.size(); i++) {
            Participant.validateJsonElement(jsonArrayparticipants.get(i));
          };
        }
      }
      if ((jsonObj.get("response_format") != null && !jsonObj.get("response_format").isJsonNull()) && !jsonObj.get("response_format").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `response_format` to be a primitive type in the JSON string but got `%s`", jsonObj.get("response_format").toString()));
      }
      if ((jsonObj.get("client_reference_id") != null && !jsonObj.get("client_reference_id").isJsonNull()) && !jsonObj.get("client_reference_id").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `client_reference_id` to be a primitive type in the JSON string but got `%s`", jsonObj.get("client_reference_id").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!AuditoriaRiscoRequest.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'AuditoriaRiscoRequest' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<AuditoriaRiscoRequest> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(AuditoriaRiscoRequest.class));

       return (TypeAdapter<T>) new TypeAdapter<AuditoriaRiscoRequest>() {
           @Override
           public void write(JsonWriter out, AuditoriaRiscoRequest value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public AuditoriaRiscoRequest read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of AuditoriaRiscoRequest given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of AuditoriaRiscoRequest
   * @throws IOException if the JSON string is invalid with respect to AuditoriaRiscoRequest
   */
  public static AuditoriaRiscoRequest fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, AuditoriaRiscoRequest.class);
  }

  /**
   * Convert an instance of AuditoriaRiscoRequest to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

