/*
 * FalaAI API
 * Transcribe, diagnose and score calls with 3 simple endpoints.  **Endpoints:** - `POST /v1/audio/transcriptions` — Audio to text - `POST /v1/analyze/diagnostic` — Conversation analysis - `POST /v1/analyze/auditoriaRisco` — Compliance audit  **Complete flow (Python):** ```python import httpx  API = 'https://api01-falaai.action.tec.br' KEY = 'fai_xxx' HD = {'Authorization': f'Bearer {KEY}'}  # 1. Transcribe files = {'file': open('call.mp3', 'rb')} resp = httpx.post(f'{API}/v1/audio/transcriptions', headers=HD, files=files, data={'model': 'falaai-transcribe-1', 'language': 'pt'}) tr = resp.json() print(f'Text: {tr[\"text\"][:100]}...')  # 2. Diagnose resp = httpx.post(f'{API}/v1/analyze/diagnostic', headers=HD, json={'dialog': tr['dialog'], 'language': 'pt-BR', 'duration_seconds': tr['duration_seconds']}) diag = resp.json() print(f'Sentiment: {diag[\"analysis\"][\"sentiment\"][\"list_choice\"]}') print(f'Summary: {diag[\"analysis\"][\"dialogue_summary\"][\"explanation\"][:100]}...')  # 3. Audit resp = httpx.post(f'{API}/v1/analyze/auditoriaRisco', headers=HD, json={'dialogo': tr['dialog'], 'duration_seconds': tr['duration_seconds']}) audit = resp.json() print(f'Score: {audit[\"audit_score\"]} | Verdict: {audit[\"verdict\"]}') print(f'Detections: {audit[\"total_detections\"]} | Violations: {len(audit[\"violations\"])} | Positives: {len(audit[\"positives\"])}') ```  **Authentication:** All endpoints require an API Key in the `Authorization` header: `Bearer fai_xxx`  Get your API Key at [falaai.action.tec.br/api](https://falaai.action.tec.br/api)
 *
 * The version of the OpenAPI document: 1.21.48
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.falaai.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonNull;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import com.falaai.JSON;

/**
 * DiagnosticCategoricalAnalysis
 */
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.25.0")
public class DiagnosticCategoricalAnalysis {
  public static final String SERIALIZED_NAME_LIST_CHOICE = "list_choice";
  @SerializedName(SERIALIZED_NAME_LIST_CHOICE)
  @jakarta.annotation.Nullable
  private String listChoice;

  public static final String SERIALIZED_NAME_JUSTIFICATION = "justification";
  @SerializedName(SERIALIZED_NAME_JUSTIFICATION)
  @jakarta.annotation.Nullable
  private String justification;

  public static final String SERIALIZED_NAME_EVIDENCE_PHRASES = "evidence_phrases";
  @SerializedName(SERIALIZED_NAME_EVIDENCE_PHRASES)
  @jakarta.annotation.Nullable
  private List<String> evidencePhrases = new ArrayList<>();

  public DiagnosticCategoricalAnalysis() {
  }

  public DiagnosticCategoricalAnalysis listChoice(@jakarta.annotation.Nullable String listChoice) {
    this.listChoice = listChoice;
    return this;
  }

  /**
   * Selected value from classification list (used in action, label, sentiment)
   * @return listChoice
   */
  @jakarta.annotation.Nullable
  public String getListChoice() {
    return listChoice;
  }

  public void setListChoice(@jakarta.annotation.Nullable String listChoice) {
    this.listChoice = listChoice;
  }


  public DiagnosticCategoricalAnalysis justification(@jakarta.annotation.Nullable String justification) {
    this.justification = justification;
    return this;
  }

  /**
   * Justification for the choice
   * @return justification
   */
  @jakarta.annotation.Nullable
  public String getJustification() {
    return justification;
  }

  public void setJustification(@jakarta.annotation.Nullable String justification) {
    this.justification = justification;
  }


  public DiagnosticCategoricalAnalysis evidencePhrases(@jakarta.annotation.Nullable List<String> evidencePhrases) {
    this.evidencePhrases = evidencePhrases;
    return this;
  }

  public DiagnosticCategoricalAnalysis addEvidencePhrasesItem(String evidencePhrasesItem) {
    if (this.evidencePhrases == null) {
      this.evidencePhrases = new ArrayList<>();
    }
    this.evidencePhrases.add(evidencePhrasesItem);
    return this;
  }

  /**
   * Verbatim transcript excerpts supporting the analysis
   * @return evidencePhrases
   */
  @jakarta.annotation.Nullable
  public List<String> getEvidencePhrases() {
    return evidencePhrases;
  }

  public void setEvidencePhrases(@jakarta.annotation.Nullable List<String> evidencePhrases) {
    this.evidencePhrases = evidencePhrases;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DiagnosticCategoricalAnalysis diagnosticCategoricalAnalysis = (DiagnosticCategoricalAnalysis) o;
    return Objects.equals(this.listChoice, diagnosticCategoricalAnalysis.listChoice) &&
        Objects.equals(this.justification, diagnosticCategoricalAnalysis.justification) &&
        Objects.equals(this.evidencePhrases, diagnosticCategoricalAnalysis.evidencePhrases);
  }

  @Override
  public int hashCode() {
    return Objects.hash(listChoice, justification, evidencePhrases);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DiagnosticCategoricalAnalysis {\n");
    sb.append("    listChoice: ").append(toIndentedString(listChoice)).append("\n");
    sb.append("    justification: ").append(toIndentedString(justification)).append("\n");
    sb.append("    evidencePhrases: ").append(toIndentedString(evidencePhrases)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("list_choice", "justification", "evidence_phrases"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(0);
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to DiagnosticCategoricalAnalysis
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!DiagnosticCategoricalAnalysis.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field(s) %s in DiagnosticCategoricalAnalysis is not found in the empty JSON string", DiagnosticCategoricalAnalysis.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!DiagnosticCategoricalAnalysis.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The field `%s` in the JSON string is not defined in the `DiagnosticCategoricalAnalysis` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("list_choice") != null && !jsonObj.get("list_choice").isJsonNull()) && !jsonObj.get("list_choice").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `list_choice` to be a primitive type in the JSON string but got `%s`", jsonObj.get("list_choice").toString()));
      }
      if ((jsonObj.get("justification") != null && !jsonObj.get("justification").isJsonNull()) && !jsonObj.get("justification").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `justification` to be a primitive type in the JSON string but got `%s`", jsonObj.get("justification").toString()));
      }
      // ensure the optional json data is an array if present
      if (jsonObj.get("evidence_phrases") != null && !jsonObj.get("evidence_phrases").isJsonNull() && !jsonObj.get("evidence_phrases").isJsonArray()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `evidence_phrases` to be an array in the JSON string but got `%s`", jsonObj.get("evidence_phrases").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!DiagnosticCategoricalAnalysis.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'DiagnosticCategoricalAnalysis' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<DiagnosticCategoricalAnalysis> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(DiagnosticCategoricalAnalysis.class));

       return (TypeAdapter<T>) new TypeAdapter<DiagnosticCategoricalAnalysis>() {
           @Override
           public void write(JsonWriter out, DiagnosticCategoricalAnalysis value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public DiagnosticCategoricalAnalysis read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of DiagnosticCategoricalAnalysis given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of DiagnosticCategoricalAnalysis
   * @throws IOException if the JSON string is invalid with respect to DiagnosticCategoricalAnalysis
   */
  public static DiagnosticCategoricalAnalysis fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, DiagnosticCategoricalAnalysis.class);
  }

  /**
   * Convert an instance of DiagnosticCategoricalAnalysis to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

