/*
 * FalaAI API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.21.49
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.falaai.model;

import java.util.Objects;
import com.falaai.model.RiskAuditUsageV2;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.math.BigDecimal;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonNull;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import com.falaai.JSON;

/**
 * RiskAuditMetaV2
 */
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.25.0")
public class RiskAuditMetaV2 {
  public static final String SERIALIZED_NAME_ID = "id";
  @SerializedName(SERIALIZED_NAME_ID)
  @jakarta.annotation.Nonnull
  private String id;

  public static final String SERIALIZED_NAME_OBJECT = "object";
  @SerializedName(SERIALIZED_NAME_OBJECT)
  @jakarta.annotation.Nullable
  private String _object = "risk_audit";

  public static final String SERIALIZED_NAME_CALL_DURATION_S = "call_duration_s";
  @SerializedName(SERIALIZED_NAME_CALL_DURATION_S)
  @jakarta.annotation.Nullable
  private BigDecimal callDurationS;

  public static final String SERIALIZED_NAME_ANALYZED_AT = "analyzed_at";
  @SerializedName(SERIALIZED_NAME_ANALYZED_AT)
  @jakarta.annotation.Nullable
  private String analyzedAt;

  public static final String SERIALIZED_NAME_USAGE = "usage";
  @SerializedName(SERIALIZED_NAME_USAGE)
  @jakarta.annotation.Nonnull
  private RiskAuditUsageV2 usage;

  public static final String SERIALIZED_NAME_CLIENT_REFERENCE_ID = "client_reference_id";
  @SerializedName(SERIALIZED_NAME_CLIENT_REFERENCE_ID)
  @jakarta.annotation.Nullable
  private String clientReferenceId;

  public RiskAuditMetaV2() {
  }

  public RiskAuditMetaV2 id(@jakarta.annotation.Nonnull String id) {
    this.id = id;
    return this;
  }

  /**
   * Analysis id
   * @return id
   */
  @jakarta.annotation.Nonnull
  public String getId() {
    return id;
  }

  public void setId(@jakarta.annotation.Nonnull String id) {
    this.id = id;
  }


  public RiskAuditMetaV2 _object(@jakarta.annotation.Nullable String _object) {
    this._object = _object;
    return this;
  }

  /**
   * Object type
   * @return _object
   */
  @jakarta.annotation.Nullable
  public String getObject() {
    return _object;
  }

  public void setObject(@jakarta.annotation.Nullable String _object) {
    this._object = _object;
  }


  public RiskAuditMetaV2 callDurationS(@jakarta.annotation.Nullable BigDecimal callDurationS) {
    this.callDurationS = callDurationS;
    return this;
  }

  /**
   * Call duration (s)
   * @return callDurationS
   */
  @jakarta.annotation.Nullable
  public BigDecimal getCallDurationS() {
    return callDurationS;
  }

  public void setCallDurationS(@jakarta.annotation.Nullable BigDecimal callDurationS) {
    this.callDurationS = callDurationS;
  }


  public RiskAuditMetaV2 analyzedAt(@jakarta.annotation.Nullable String analyzedAt) {
    this.analyzedAt = analyzedAt;
    return this;
  }

  /**
   * ISO 8601 analyzed timestamp
   * @return analyzedAt
   */
  @jakarta.annotation.Nullable
  public String getAnalyzedAt() {
    return analyzedAt;
  }

  public void setAnalyzedAt(@jakarta.annotation.Nullable String analyzedAt) {
    this.analyzedAt = analyzedAt;
  }


  public RiskAuditMetaV2 usage(@jakarta.annotation.Nonnull RiskAuditUsageV2 usage) {
    this.usage = usage;
    return this;
  }

  /**
   * Usage block
   * @return usage
   */
  @jakarta.annotation.Nonnull
  public RiskAuditUsageV2 getUsage() {
    return usage;
  }

  public void setUsage(@jakarta.annotation.Nonnull RiskAuditUsageV2 usage) {
    this.usage = usage;
  }


  public RiskAuditMetaV2 clientReferenceId(@jakarta.annotation.Nullable String clientReferenceId) {
    this.clientReferenceId = clientReferenceId;
    return this;
  }

  /**
   * Echoed client reference id
   * @return clientReferenceId
   */
  @jakarta.annotation.Nullable
  public String getClientReferenceId() {
    return clientReferenceId;
  }

  public void setClientReferenceId(@jakarta.annotation.Nullable String clientReferenceId) {
    this.clientReferenceId = clientReferenceId;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RiskAuditMetaV2 riskAuditMetaV2 = (RiskAuditMetaV2) o;
    return Objects.equals(this.id, riskAuditMetaV2.id) &&
        Objects.equals(this._object, riskAuditMetaV2._object) &&
        Objects.equals(this.callDurationS, riskAuditMetaV2.callDurationS) &&
        Objects.equals(this.analyzedAt, riskAuditMetaV2.analyzedAt) &&
        Objects.equals(this.usage, riskAuditMetaV2.usage) &&
        Objects.equals(this.clientReferenceId, riskAuditMetaV2.clientReferenceId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, _object, callDurationS, analyzedAt, usage, clientReferenceId);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RiskAuditMetaV2 {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    _object: ").append(toIndentedString(_object)).append("\n");
    sb.append("    callDurationS: ").append(toIndentedString(callDurationS)).append("\n");
    sb.append("    analyzedAt: ").append(toIndentedString(analyzedAt)).append("\n");
    sb.append("    usage: ").append(toIndentedString(usage)).append("\n");
    sb.append("    clientReferenceId: ").append(toIndentedString(clientReferenceId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("id", "object", "call_duration_s", "analyzed_at", "usage", "client_reference_id"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(Arrays.asList("id", "usage"));
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to RiskAuditMetaV2
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!RiskAuditMetaV2.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field(s) %s in RiskAuditMetaV2 is not found in the empty JSON string", RiskAuditMetaV2.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!RiskAuditMetaV2.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The field `%s` in the JSON string is not defined in the `RiskAuditMetaV2` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : RiskAuditMetaV2.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if (!jsonObj.get("id").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `id` to be a primitive type in the JSON string but got `%s`", jsonObj.get("id").toString()));
      }
      if ((jsonObj.get("object") != null && !jsonObj.get("object").isJsonNull()) && !jsonObj.get("object").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `object` to be a primitive type in the JSON string but got `%s`", jsonObj.get("object").toString()));
      }
      if ((jsonObj.get("analyzed_at") != null && !jsonObj.get("analyzed_at").isJsonNull()) && !jsonObj.get("analyzed_at").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `analyzed_at` to be a primitive type in the JSON string but got `%s`", jsonObj.get("analyzed_at").toString()));
      }
      // validate the required field `usage`
      RiskAuditUsageV2.validateJsonElement(jsonObj.get("usage"));
      if ((jsonObj.get("client_reference_id") != null && !jsonObj.get("client_reference_id").isJsonNull()) && !jsonObj.get("client_reference_id").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `client_reference_id` to be a primitive type in the JSON string but got `%s`", jsonObj.get("client_reference_id").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!RiskAuditMetaV2.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'RiskAuditMetaV2' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<RiskAuditMetaV2> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(RiskAuditMetaV2.class));

       return (TypeAdapter<T>) new TypeAdapter<RiskAuditMetaV2>() {
           @Override
           public void write(JsonWriter out, RiskAuditMetaV2 value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public RiskAuditMetaV2 read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of RiskAuditMetaV2 given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of RiskAuditMetaV2
   * @throws IOException if the JSON string is invalid with respect to RiskAuditMetaV2
   */
  public static RiskAuditMetaV2 fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, RiskAuditMetaV2.class);
  }

  /**
   * Convert an instance of RiskAuditMetaV2 to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

