/*
 * FalaAI API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.21.49
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.falaai.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonNull;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import com.falaai.JSON;

/**
 * RiskAuditParticipantV2
 */
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.25.0")
public class RiskAuditParticipantV2 {
  public static final String SERIALIZED_NAME_INTERLOCUTOR = "interlocutor";
  @SerializedName(SERIALIZED_NAME_INTERLOCUTOR)
  @jakarta.annotation.Nullable
  private String interlocutor;

  public static final String SERIALIZED_NAME_NAME = "name";
  @SerializedName(SERIALIZED_NAME_NAME)
  @jakarta.annotation.Nullable
  private String name;

  public static final String SERIALIZED_NAME_ROLE = "role";
  @SerializedName(SERIALIZED_NAME_ROLE)
  @jakarta.annotation.Nullable
  private String role;

  public static final String SERIALIZED_NAME_CONFIDENCE = "confidence";
  @SerializedName(SERIALIZED_NAME_CONFIDENCE)
  @jakarta.annotation.Nullable
  private String confidence;

  public static final String SERIALIZED_NAME_SOURCE = "source";
  @SerializedName(SERIALIZED_NAME_SOURCE)
  @jakarta.annotation.Nullable
  private String source;

  public static final String SERIALIZED_NAME_EVIDENCE = "evidence";
  @SerializedName(SERIALIZED_NAME_EVIDENCE)
  @jakarta.annotation.Nullable
  private String evidence;

  public RiskAuditParticipantV2() {
  }

  public RiskAuditParticipantV2 interlocutor(@jakarta.annotation.Nullable String interlocutor) {
    this.interlocutor = interlocutor;
    return this;
  }

  /**
   * Speaker label
   * @return interlocutor
   */
  @jakarta.annotation.Nullable
  public String getInterlocutor() {
    return interlocutor;
  }

  public void setInterlocutor(@jakarta.annotation.Nullable String interlocutor) {
    this.interlocutor = interlocutor;
  }


  public RiskAuditParticipantV2 name(@jakarta.annotation.Nullable String name) {
    this.name = name;
    return this;
  }

  /**
   * Participant name
   * @return name
   */
  @jakarta.annotation.Nullable
  public String getName() {
    return name;
  }

  public void setName(@jakarta.annotation.Nullable String name) {
    this.name = name;
  }


  public RiskAuditParticipantV2 role(@jakarta.annotation.Nullable String role) {
    this.role = role;
    return this;
  }

  /**
   * Role (agent/client/bot/unknown)
   * @return role
   */
  @jakarta.annotation.Nullable
  public String getRole() {
    return role;
  }

  public void setRole(@jakarta.annotation.Nullable String role) {
    this.role = role;
  }


  public RiskAuditParticipantV2 confidence(@jakarta.annotation.Nullable String confidence) {
    this.confidence = confidence;
    return this;
  }

  /**
   * Role inference confidence (high/medium/low)
   * @return confidence
   */
  @jakarta.annotation.Nullable
  public String getConfidence() {
    return confidence;
  }

  public void setConfidence(@jakarta.annotation.Nullable String confidence) {
    this.confidence = confidence;
  }


  public RiskAuditParticipantV2 source(@jakarta.annotation.Nullable String source) {
    this.source = source;
    return this;
  }

  /**
   * Role source (input/inferred)
   * @return source
   */
  @jakarta.annotation.Nullable
  public String getSource() {
    return source;
  }

  public void setSource(@jakarta.annotation.Nullable String source) {
    this.source = source;
  }


  public RiskAuditParticipantV2 evidence(@jakarta.annotation.Nullable String evidence) {
    this.evidence = evidence;
    return this;
  }

  /**
   * Role inference evidence
   * @return evidence
   */
  @jakarta.annotation.Nullable
  public String getEvidence() {
    return evidence;
  }

  public void setEvidence(@jakarta.annotation.Nullable String evidence) {
    this.evidence = evidence;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RiskAuditParticipantV2 riskAuditParticipantV2 = (RiskAuditParticipantV2) o;
    return Objects.equals(this.interlocutor, riskAuditParticipantV2.interlocutor) &&
        Objects.equals(this.name, riskAuditParticipantV2.name) &&
        Objects.equals(this.role, riskAuditParticipantV2.role) &&
        Objects.equals(this.confidence, riskAuditParticipantV2.confidence) &&
        Objects.equals(this.source, riskAuditParticipantV2.source) &&
        Objects.equals(this.evidence, riskAuditParticipantV2.evidence);
  }

  @Override
  public int hashCode() {
    return Objects.hash(interlocutor, name, role, confidence, source, evidence);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RiskAuditParticipantV2 {\n");
    sb.append("    interlocutor: ").append(toIndentedString(interlocutor)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    role: ").append(toIndentedString(role)).append("\n");
    sb.append("    confidence: ").append(toIndentedString(confidence)).append("\n");
    sb.append("    source: ").append(toIndentedString(source)).append("\n");
    sb.append("    evidence: ").append(toIndentedString(evidence)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("interlocutor", "name", "role", "confidence", "source", "evidence"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(0);
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to RiskAuditParticipantV2
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!RiskAuditParticipantV2.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field(s) %s in RiskAuditParticipantV2 is not found in the empty JSON string", RiskAuditParticipantV2.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!RiskAuditParticipantV2.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The field `%s` in the JSON string is not defined in the `RiskAuditParticipantV2` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("interlocutor") != null && !jsonObj.get("interlocutor").isJsonNull()) && !jsonObj.get("interlocutor").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `interlocutor` to be a primitive type in the JSON string but got `%s`", jsonObj.get("interlocutor").toString()));
      }
      if ((jsonObj.get("name") != null && !jsonObj.get("name").isJsonNull()) && !jsonObj.get("name").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `name` to be a primitive type in the JSON string but got `%s`", jsonObj.get("name").toString()));
      }
      if ((jsonObj.get("role") != null && !jsonObj.get("role").isJsonNull()) && !jsonObj.get("role").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `role` to be a primitive type in the JSON string but got `%s`", jsonObj.get("role").toString()));
      }
      if ((jsonObj.get("confidence") != null && !jsonObj.get("confidence").isJsonNull()) && !jsonObj.get("confidence").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `confidence` to be a primitive type in the JSON string but got `%s`", jsonObj.get("confidence").toString()));
      }
      if ((jsonObj.get("source") != null && !jsonObj.get("source").isJsonNull()) && !jsonObj.get("source").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `source` to be a primitive type in the JSON string but got `%s`", jsonObj.get("source").toString()));
      }
      if ((jsonObj.get("evidence") != null && !jsonObj.get("evidence").isJsonNull()) && !jsonObj.get("evidence").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `evidence` to be a primitive type in the JSON string but got `%s`", jsonObj.get("evidence").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!RiskAuditParticipantV2.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'RiskAuditParticipantV2' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<RiskAuditParticipantV2> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(RiskAuditParticipantV2.class));

       return (TypeAdapter<T>) new TypeAdapter<RiskAuditParticipantV2>() {
           @Override
           public void write(JsonWriter out, RiskAuditParticipantV2 value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public RiskAuditParticipantV2 read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of RiskAuditParticipantV2 given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of RiskAuditParticipantV2
   * @throws IOException if the JSON string is invalid with respect to RiskAuditParticipantV2
   */
  public static RiskAuditParticipantV2 fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, RiskAuditParticipantV2.class);
  }

  /**
   * Convert an instance of RiskAuditParticipantV2 to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

