/*
 * FalaAI API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.21.49
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.falaai.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonNull;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import com.falaai.JSON;

/**
 * RiskAuditUsageV2
 */
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.25.0")
public class RiskAuditUsageV2 {
  public static final String SERIALIZED_NAME_CHARACTERS = "characters";
  @SerializedName(SERIALIZED_NAME_CHARACTERS)
  @jakarta.annotation.Nonnull
  private Integer characters;

  public static final String SERIALIZED_NAME_CREDITS_CONSUMED = "credits_consumed";
  @SerializedName(SERIALIZED_NAME_CREDITS_CONSUMED)
  @jakarta.annotation.Nonnull
  private Integer creditsConsumed;

  public static final String SERIALIZED_NAME_PROCESSING_MS = "processing_ms";
  @SerializedName(SERIALIZED_NAME_PROCESSING_MS)
  @jakarta.annotation.Nonnull
  private Integer processingMs;

  public RiskAuditUsageV2() {
  }

  public RiskAuditUsageV2 characters(@jakarta.annotation.Nonnull Integer characters) {
    this.characters = characters;
    return this;
  }

  /**
   * Characters analyzed
   * @return characters
   */
  @jakarta.annotation.Nonnull
  public Integer getCharacters() {
    return characters;
  }

  public void setCharacters(@jakarta.annotation.Nonnull Integer characters) {
    this.characters = characters;
  }


  public RiskAuditUsageV2 creditsConsumed(@jakarta.annotation.Nonnull Integer creditsConsumed) {
    this.creditsConsumed = creditsConsumed;
    return this;
  }

  /**
   * Credits consumed
   * @return creditsConsumed
   */
  @jakarta.annotation.Nonnull
  public Integer getCreditsConsumed() {
    return creditsConsumed;
  }

  public void setCreditsConsumed(@jakarta.annotation.Nonnull Integer creditsConsumed) {
    this.creditsConsumed = creditsConsumed;
  }


  public RiskAuditUsageV2 processingMs(@jakarta.annotation.Nonnull Integer processingMs) {
    this.processingMs = processingMs;
    return this;
  }

  /**
   * Processing time (ms)
   * @return processingMs
   */
  @jakarta.annotation.Nonnull
  public Integer getProcessingMs() {
    return processingMs;
  }

  public void setProcessingMs(@jakarta.annotation.Nonnull Integer processingMs) {
    this.processingMs = processingMs;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RiskAuditUsageV2 riskAuditUsageV2 = (RiskAuditUsageV2) o;
    return Objects.equals(this.characters, riskAuditUsageV2.characters) &&
        Objects.equals(this.creditsConsumed, riskAuditUsageV2.creditsConsumed) &&
        Objects.equals(this.processingMs, riskAuditUsageV2.processingMs);
  }

  @Override
  public int hashCode() {
    return Objects.hash(characters, creditsConsumed, processingMs);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RiskAuditUsageV2 {\n");
    sb.append("    characters: ").append(toIndentedString(characters)).append("\n");
    sb.append("    creditsConsumed: ").append(toIndentedString(creditsConsumed)).append("\n");
    sb.append("    processingMs: ").append(toIndentedString(processingMs)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("characters", "credits_consumed", "processing_ms"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(Arrays.asList("characters", "credits_consumed", "processing_ms"));
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to RiskAuditUsageV2
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!RiskAuditUsageV2.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field(s) %s in RiskAuditUsageV2 is not found in the empty JSON string", RiskAuditUsageV2.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!RiskAuditUsageV2.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The field `%s` in the JSON string is not defined in the `RiskAuditUsageV2` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : RiskAuditUsageV2.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!RiskAuditUsageV2.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'RiskAuditUsageV2' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<RiskAuditUsageV2> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(RiskAuditUsageV2.class));

       return (TypeAdapter<T>) new TypeAdapter<RiskAuditUsageV2>() {
           @Override
           public void write(JsonWriter out, RiskAuditUsageV2 value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public RiskAuditUsageV2 read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of RiskAuditUsageV2 given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of RiskAuditUsageV2
   * @throws IOException if the JSON string is invalid with respect to RiskAuditUsageV2
   */
  public static RiskAuditUsageV2 fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, RiskAuditUsageV2.class);
  }

  /**
   * Convert an instance of RiskAuditUsageV2 to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

