/*
 * FalaAI API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.21.49
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.falaai.model;

import java.util.Objects;
import com.falaai.model.RiskAuditAnalysisV2;
import com.falaai.model.RiskAuditAudioEventModelV2;
import com.falaai.model.RiskAuditAuditDecisionsV2;
import com.falaai.model.RiskAuditDetectionsV2;
import com.falaai.model.RiskAuditIndexerV2;
import com.falaai.model.RiskAuditMetaV2;
import com.falaai.model.RiskAuditParticipantsV2;
import com.falaai.model.RiskAuditScoresV2;
import com.falaai.model.RiskAuditScoringExplanationV2;
import com.falaai.model.RiskAuditSummaryV2;
import com.falaai.model.RiskAuditTimelineV2;
import com.falaai.model.RiskAuditVerdictV2;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import java.util.HashMap;
import java.util.Map;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonNull;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import com.falaai.JSON;

/**
 * Response V2 (build_public_response_v2) — blocos logicos EN-US. Fonte: response_builder.py.
 */
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.25.0")
public class RiskAuditV2 {
  public static final String SERIALIZED_NAME_META = "meta";
  @SerializedName(SERIALIZED_NAME_META)
  @jakarta.annotation.Nonnull
  private RiskAuditMetaV2 meta;

  public static final String SERIALIZED_NAME_PARTICIPANTS = "participants";
  @SerializedName(SERIALIZED_NAME_PARTICIPANTS)
  @jakarta.annotation.Nonnull
  private RiskAuditParticipantsV2 participants;

  public static final String SERIALIZED_NAME_VERDICT = "verdict";
  @SerializedName(SERIALIZED_NAME_VERDICT)
  @jakarta.annotation.Nonnull
  private RiskAuditVerdictV2 verdict;

  public static final String SERIALIZED_NAME_SCORES = "scores";
  @SerializedName(SERIALIZED_NAME_SCORES)
  @jakarta.annotation.Nonnull
  private RiskAuditScoresV2 scores;

  public static final String SERIALIZED_NAME_DETECTIONS = "detections";
  @SerializedName(SERIALIZED_NAME_DETECTIONS)
  @jakarta.annotation.Nonnull
  private RiskAuditDetectionsV2 detections;

  public static final String SERIALIZED_NAME_ANALYSIS = "analysis";
  @SerializedName(SERIALIZED_NAME_ANALYSIS)
  @jakarta.annotation.Nonnull
  private RiskAuditAnalysisV2 analysis;

  public static final String SERIALIZED_NAME_TIMELINE = "timeline";
  @SerializedName(SERIALIZED_NAME_TIMELINE)
  @jakarta.annotation.Nonnull
  private RiskAuditTimelineV2 timeline;

  public static final String SERIALIZED_NAME_AUDIO_EVENT_MODEL = "audio_event_model";
  @SerializedName(SERIALIZED_NAME_AUDIO_EVENT_MODEL)
  @jakarta.annotation.Nonnull
  private RiskAuditAudioEventModelV2 audioEventModel;

  public static final String SERIALIZED_NAME_CATEGORIES_SUMMARY = "categories_summary";
  @SerializedName(SERIALIZED_NAME_CATEGORIES_SUMMARY)
  @jakarta.annotation.Nonnull
  private Map<String, Object> categoriesSummary = new HashMap<>();

  public static final String SERIALIZED_NAME_INDEXER = "indexer";
  @SerializedName(SERIALIZED_NAME_INDEXER)
  @jakarta.annotation.Nonnull
  private RiskAuditIndexerV2 indexer;

  public static final String SERIALIZED_NAME_SUMMARY = "summary";
  @SerializedName(SERIALIZED_NAME_SUMMARY)
  @jakarta.annotation.Nonnull
  private RiskAuditSummaryV2 summary;

  public static final String SERIALIZED_NAME_ACTIONS_I18N = "actions_i18n";
  @SerializedName(SERIALIZED_NAME_ACTIONS_I18N)
  @jakarta.annotation.Nonnull
  private Map<String, Object> actionsI18n = new HashMap<>();

  public static final String SERIALIZED_NAME_AUDIT_DECISIONS = "audit_decisions";
  @SerializedName(SERIALIZED_NAME_AUDIT_DECISIONS)
  @jakarta.annotation.Nonnull
  private RiskAuditAuditDecisionsV2 auditDecisions;

  public static final String SERIALIZED_NAME_SCORING_EXPLANATION = "scoring_explanation";
  @SerializedName(SERIALIZED_NAME_SCORING_EXPLANATION)
  @jakarta.annotation.Nonnull
  private RiskAuditScoringExplanationV2 scoringExplanation;

  public static final String SERIALIZED_NAME_HTML_REPORT = "html_report";
  @SerializedName(SERIALIZED_NAME_HTML_REPORT)
  @jakarta.annotation.Nonnull
  private String htmlReport;

  public RiskAuditV2() {
  }

  public RiskAuditV2 meta(@jakarta.annotation.Nonnull RiskAuditMetaV2 meta) {
    this.meta = meta;
    return this;
  }

  /**
   * Identification + usage
   * @return meta
   */
  @jakarta.annotation.Nonnull
  public RiskAuditMetaV2 getMeta() {
    return meta;
  }

  public void setMeta(@jakarta.annotation.Nonnull RiskAuditMetaV2 meta) {
    this.meta = meta;
  }


  public RiskAuditV2 participants(@jakarta.annotation.Nonnull RiskAuditParticipantsV2 participants) {
    this.participants = participants;
    return this;
  }

  /**
   * Participants/roles/direction
   * @return participants
   */
  @jakarta.annotation.Nonnull
  public RiskAuditParticipantsV2 getParticipants() {
    return participants;
  }

  public void setParticipants(@jakarta.annotation.Nonnull RiskAuditParticipantsV2 participants) {
    this.participants = participants;
  }


  public RiskAuditV2 verdict(@jakarta.annotation.Nonnull RiskAuditVerdictV2 verdict) {
    this.verdict = verdict;
    return this;
  }

  /**
   * Verdict + level + applied actions
   * @return verdict
   */
  @jakarta.annotation.Nonnull
  public RiskAuditVerdictV2 getVerdict() {
    return verdict;
  }

  public void setVerdict(@jakarta.annotation.Nonnull RiskAuditVerdictV2 verdict) {
    this.verdict = verdict;
  }


  public RiskAuditV2 scores(@jakarta.annotation.Nonnull RiskAuditScoresV2 scores) {
    this.scores = scores;
    return this;
  }

  /**
   * Consolidated + per-participant scores
   * @return scores
   */
  @jakarta.annotation.Nonnull
  public RiskAuditScoresV2 getScores() {
    return scores;
  }

  public void setScores(@jakarta.annotation.Nonnull RiskAuditScoresV2 scores) {
    this.scores = scores;
  }


  public RiskAuditV2 detections(@jakarta.annotation.Nonnull RiskAuditDetectionsV2 detections) {
    this.detections = detections;
    return this;
  }

  /**
   * violations/positives/client alerts
   * @return detections
   */
  @jakarta.annotation.Nonnull
  public RiskAuditDetectionsV2 getDetections() {
    return detections;
  }

  public void setDetections(@jakarta.annotation.Nonnull RiskAuditDetectionsV2 detections) {
    this.detections = detections;
  }


  public RiskAuditV2 analysis(@jakarta.annotation.Nonnull RiskAuditAnalysisV2 analysis) {
    this.analysis = analysis;
    return this;
  }

  /**
   * global_metrics + final_analysis + frameworks
   * @return analysis
   */
  @jakarta.annotation.Nonnull
  public RiskAuditAnalysisV2 getAnalysis() {
    return analysis;
  }

  public void setAnalysis(@jakarta.annotation.Nonnull RiskAuditAnalysisV2 analysis) {
    this.analysis = analysis;
  }


  public RiskAuditV2 timeline(@jakarta.annotation.Nonnull RiskAuditTimelineV2 timeline) {
    this.timeline = timeline;
    return this;
  }

  /**
   * turns_sentiment + audio_events + groups
   * @return timeline
   */
  @jakarta.annotation.Nonnull
  public RiskAuditTimelineV2 getTimeline() {
    return timeline;
  }

  public void setTimeline(@jakarta.annotation.Nonnull RiskAuditTimelineV2 timeline) {
    this.timeline = timeline;
  }


  public RiskAuditV2 audioEventModel(@jakarta.annotation.Nonnull RiskAuditAudioEventModelV2 audioEventModel) {
    this.audioEventModel = audioEventModel;
    return this;
  }

  /**
   * MAC audio event semantics
   * @return audioEventModel
   */
  @jakarta.annotation.Nonnull
  public RiskAuditAudioEventModelV2 getAudioEventModel() {
    return audioEventModel;
  }

  public void setAudioEventModel(@jakarta.annotation.Nonnull RiskAuditAudioEventModelV2 audioEventModel) {
    this.audioEventModel = audioEventModel;
  }


  public RiskAuditV2 categoriesSummary(@jakarta.annotation.Nonnull Map<String, Object> categoriesSummary) {
    this.categoriesSummary = categoriesSummary;
    return this;
  }

  public RiskAuditV2 putCategoriesSummaryItem(String key, Object categoriesSummaryItem) {
    if (this.categoriesSummary == null) {
      this.categoriesSummary = new HashMap<>();
    }
    this.categoriesSummary.put(key, categoriesSummaryItem);
    return this;
  }

  /**
   * Per-category summary (keyed by category)
   * @return categoriesSummary
   */
  @jakarta.annotation.Nonnull
  public Map<String, Object> getCategoriesSummary() {
    return categoriesSummary;
  }

  public void setCategoriesSummary(@jakarta.annotation.Nonnull Map<String, Object> categoriesSummary) {
    this.categoriesSummary = categoriesSummary;
  }


  public RiskAuditV2 indexer(@jakarta.annotation.Nonnull RiskAuditIndexerV2 indexer) {
    this.indexer = indexer;
    return this;
  }

  /**
   * Suggested terms for bank
   * @return indexer
   */
  @jakarta.annotation.Nonnull
  public RiskAuditIndexerV2 getIndexer() {
    return indexer;
  }

  public void setIndexer(@jakarta.annotation.Nonnull RiskAuditIndexerV2 indexer) {
    this.indexer = indexer;
  }


  public RiskAuditV2 summary(@jakarta.annotation.Nonnull RiskAuditSummaryV2 summary) {
    this.summary = summary;
    return this;
  }

  /**
   * Executive summary counts
   * @return summary
   */
  @jakarta.annotation.Nonnull
  public RiskAuditSummaryV2 getSummary() {
    return summary;
  }

  public void setSummary(@jakarta.annotation.Nonnull RiskAuditSummaryV2 summary) {
    this.summary = summary;
  }


  public RiskAuditV2 actionsI18n(@jakarta.annotation.Nonnull Map<String, Object> actionsI18n) {
    this.actionsI18n = actionsI18n;
    return this;
  }

  public RiskAuditV2 putActionsI18nItem(String key, Object actionsI18nItem) {
    if (this.actionsI18n == null) {
      this.actionsI18n = new HashMap<>();
    }
    this.actionsI18n.put(key, actionsI18nItem);
    return this;
  }

  /**
   * Used actions i18n catalog (keyed by action)
   * @return actionsI18n
   */
  @jakarta.annotation.Nonnull
  public Map<String, Object> getActionsI18n() {
    return actionsI18n;
  }

  public void setActionsI18n(@jakarta.annotation.Nonnull Map<String, Object> actionsI18n) {
    this.actionsI18n = actionsI18n;
  }


  public RiskAuditV2 auditDecisions(@jakarta.annotation.Nonnull RiskAuditAuditDecisionsV2 auditDecisions) {
    this.auditDecisions = auditDecisions;
    return this;
  }

  /**
   * Risk origin + validator changes
   * @return auditDecisions
   */
  @jakarta.annotation.Nonnull
  public RiskAuditAuditDecisionsV2 getAuditDecisions() {
    return auditDecisions;
  }

  public void setAuditDecisions(@jakarta.annotation.Nonnull RiskAuditAuditDecisionsV2 auditDecisions) {
    this.auditDecisions = auditDecisions;
  }


  public RiskAuditV2 scoringExplanation(@jakarta.annotation.Nonnull RiskAuditScoringExplanationV2 scoringExplanation) {
    this.scoringExplanation = scoringExplanation;
    return this;
  }

  /**
   * Score composition explanation
   * @return scoringExplanation
   */
  @jakarta.annotation.Nonnull
  public RiskAuditScoringExplanationV2 getScoringExplanation() {
    return scoringExplanation;
  }

  public void setScoringExplanation(@jakarta.annotation.Nonnull RiskAuditScoringExplanationV2 scoringExplanation) {
    this.scoringExplanation = scoringExplanation;
  }


  public RiskAuditV2 htmlReport(@jakarta.annotation.Nonnull String htmlReport) {
    this.htmlReport = htmlReport;
    return this;
  }

  /**
   * HTML report (base64 gzip)
   * @return htmlReport
   */
  @jakarta.annotation.Nonnull
  public String getHtmlReport() {
    return htmlReport;
  }

  public void setHtmlReport(@jakarta.annotation.Nonnull String htmlReport) {
    this.htmlReport = htmlReport;
  }

  /**
   * A container for additional, undeclared properties.
   * This is a holder for any undeclared properties as specified with
   * the 'additionalProperties' keyword in the OAS document.
   */
  private Map<String, Object> additionalProperties;

  /**
   * Set the additional (undeclared) property with the specified name and value.
   * If the property does not already exist, create it otherwise replace it.
   *
   * @param key name of the property
   * @param value value of the property
   * @return the RiskAuditV2 instance itself
   */
  public RiskAuditV2 putAdditionalProperty(String key, Object value) {
    if (this.additionalProperties == null) {
        this.additionalProperties = new HashMap<String, Object>();
    }
    this.additionalProperties.put(key, value);
    return this;
  }

  /**
   * Return the additional (undeclared) property.
   *
   * @return a map of objects
   */
  public Map<String, Object> getAdditionalProperties() {
    return additionalProperties;
  }

  /**
   * Return the additional (undeclared) property with the specified name.
   *
   * @param key name of the property
   * @return an object
   */
  public Object getAdditionalProperty(String key) {
    if (this.additionalProperties == null) {
        return null;
    }
    return this.additionalProperties.get(key);
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RiskAuditV2 riskAuditV2 = (RiskAuditV2) o;
    return Objects.equals(this.meta, riskAuditV2.meta) &&
        Objects.equals(this.participants, riskAuditV2.participants) &&
        Objects.equals(this.verdict, riskAuditV2.verdict) &&
        Objects.equals(this.scores, riskAuditV2.scores) &&
        Objects.equals(this.detections, riskAuditV2.detections) &&
        Objects.equals(this.analysis, riskAuditV2.analysis) &&
        Objects.equals(this.timeline, riskAuditV2.timeline) &&
        Objects.equals(this.audioEventModel, riskAuditV2.audioEventModel) &&
        Objects.equals(this.categoriesSummary, riskAuditV2.categoriesSummary) &&
        Objects.equals(this.indexer, riskAuditV2.indexer) &&
        Objects.equals(this.summary, riskAuditV2.summary) &&
        Objects.equals(this.actionsI18n, riskAuditV2.actionsI18n) &&
        Objects.equals(this.auditDecisions, riskAuditV2.auditDecisions) &&
        Objects.equals(this.scoringExplanation, riskAuditV2.scoringExplanation) &&
        Objects.equals(this.htmlReport, riskAuditV2.htmlReport)&&
        Objects.equals(this.additionalProperties, riskAuditV2.additionalProperties);
  }

  @Override
  public int hashCode() {
    return Objects.hash(meta, participants, verdict, scores, detections, analysis, timeline, audioEventModel, categoriesSummary, indexer, summary, actionsI18n, auditDecisions, scoringExplanation, htmlReport, additionalProperties);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RiskAuditV2 {\n");
    sb.append("    meta: ").append(toIndentedString(meta)).append("\n");
    sb.append("    participants: ").append(toIndentedString(participants)).append("\n");
    sb.append("    verdict: ").append(toIndentedString(verdict)).append("\n");
    sb.append("    scores: ").append(toIndentedString(scores)).append("\n");
    sb.append("    detections: ").append(toIndentedString(detections)).append("\n");
    sb.append("    analysis: ").append(toIndentedString(analysis)).append("\n");
    sb.append("    timeline: ").append(toIndentedString(timeline)).append("\n");
    sb.append("    audioEventModel: ").append(toIndentedString(audioEventModel)).append("\n");
    sb.append("    categoriesSummary: ").append(toIndentedString(categoriesSummary)).append("\n");
    sb.append("    indexer: ").append(toIndentedString(indexer)).append("\n");
    sb.append("    summary: ").append(toIndentedString(summary)).append("\n");
    sb.append("    actionsI18n: ").append(toIndentedString(actionsI18n)).append("\n");
    sb.append("    auditDecisions: ").append(toIndentedString(auditDecisions)).append("\n");
    sb.append("    scoringExplanation: ").append(toIndentedString(scoringExplanation)).append("\n");
    sb.append("    htmlReport: ").append(toIndentedString(htmlReport)).append("\n");
    sb.append("    additionalProperties: ").append(toIndentedString(additionalProperties)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("meta", "participants", "verdict", "scores", "detections", "analysis", "timeline", "audio_event_model", "categories_summary", "indexer", "summary", "actions_i18n", "audit_decisions", "scoring_explanation", "html_report"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(Arrays.asList("meta", "participants", "verdict", "scores", "detections", "analysis", "timeline", "audio_event_model", "categories_summary", "indexer", "summary", "actions_i18n", "audit_decisions", "scoring_explanation", "html_report"));
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to RiskAuditV2
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!RiskAuditV2.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field(s) %s in RiskAuditV2 is not found in the empty JSON string", RiskAuditV2.openapiRequiredFields.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : RiskAuditV2.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      // validate the required field `meta`
      RiskAuditMetaV2.validateJsonElement(jsonObj.get("meta"));
      // validate the required field `participants`
      RiskAuditParticipantsV2.validateJsonElement(jsonObj.get("participants"));
      // validate the required field `verdict`
      RiskAuditVerdictV2.validateJsonElement(jsonObj.get("verdict"));
      // validate the required field `scores`
      RiskAuditScoresV2.validateJsonElement(jsonObj.get("scores"));
      // validate the required field `detections`
      RiskAuditDetectionsV2.validateJsonElement(jsonObj.get("detections"));
      // validate the required field `analysis`
      RiskAuditAnalysisV2.validateJsonElement(jsonObj.get("analysis"));
      // validate the required field `timeline`
      RiskAuditTimelineV2.validateJsonElement(jsonObj.get("timeline"));
      // validate the required field `audio_event_model`
      RiskAuditAudioEventModelV2.validateJsonElement(jsonObj.get("audio_event_model"));
      // validate the required field `indexer`
      RiskAuditIndexerV2.validateJsonElement(jsonObj.get("indexer"));
      // validate the required field `summary`
      RiskAuditSummaryV2.validateJsonElement(jsonObj.get("summary"));
      // validate the required field `audit_decisions`
      RiskAuditAuditDecisionsV2.validateJsonElement(jsonObj.get("audit_decisions"));
      // validate the required field `scoring_explanation`
      RiskAuditScoringExplanationV2.validateJsonElement(jsonObj.get("scoring_explanation"));
      if (!jsonObj.get("html_report").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `html_report` to be a primitive type in the JSON string but got `%s`", jsonObj.get("html_report").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!RiskAuditV2.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'RiskAuditV2' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<RiskAuditV2> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(RiskAuditV2.class));

       return (TypeAdapter<T>) new TypeAdapter<RiskAuditV2>() {
           @Override
           public void write(JsonWriter out, RiskAuditV2 value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             obj.remove("additionalProperties");
             // serialize additional properties
             if (value.getAdditionalProperties() != null) {
               for (Map.Entry<String, Object> entry : value.getAdditionalProperties().entrySet()) {
                 if (entry.getValue() instanceof String)
                   obj.addProperty(entry.getKey(), (String) entry.getValue());
                 else if (entry.getValue() instanceof Number)
                   obj.addProperty(entry.getKey(), (Number) entry.getValue());
                 else if (entry.getValue() instanceof Boolean)
                   obj.addProperty(entry.getKey(), (Boolean) entry.getValue());
                 else if (entry.getValue() instanceof Character)
                   obj.addProperty(entry.getKey(), (Character) entry.getValue());
                 else {
                   JsonElement jsonElement = gson.toJsonTree(entry.getValue());
                   if (jsonElement.isJsonNull()) {
                     obj.add(entry.getKey(), JsonNull.INSTANCE);
                   } else if (jsonElement.isJsonArray()) {
                     obj.add(entry.getKey(), jsonElement.getAsJsonArray());
                   } else {
                     obj.add(entry.getKey(), jsonElement.getAsJsonObject());
                   }
                 }
               }
             }
             elementAdapter.write(out, obj);
           }

           @Override
           public RiskAuditV2 read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             JsonObject jsonObj = jsonElement.getAsJsonObject();
             // store additional fields in the deserialized instance
             RiskAuditV2 instance = thisAdapter.fromJsonTree(jsonObj);
             for (Map.Entry<String, JsonElement> entry : jsonObj.entrySet()) {
               if (!openapiFields.contains(entry.getKey())) {
                 if (entry.getValue().isJsonPrimitive()) { // primitive type
                   if (entry.getValue().getAsJsonPrimitive().isString())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsString());
                   else if (entry.getValue().getAsJsonPrimitive().isNumber())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsNumber());
                   else if (entry.getValue().getAsJsonPrimitive().isBoolean())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsBoolean());
                   else
                     throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The field `%s` has unknown primitive type. Value: %s", entry.getKey(), entry.getValue().toString()));
                 } else if (entry.getValue().isJsonArray()) {
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), List.class));
                 } else { // JSON object
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), HashMap.class));
                 }
               }
             }
             return instance;
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of RiskAuditV2 given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of RiskAuditV2
   * @throws IOException if the JSON string is invalid with respect to RiskAuditV2
   */
  public static RiskAuditV2 fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, RiskAuditV2.class);
  }

  /**
   * Convert an instance of RiskAuditV2 to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

