/*
 * FalaAI API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.21.49
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.falaai.model;

import java.util.Objects;
import com.falaai.model.RiskAuditDetectionItemV2;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.util.Map;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonNull;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import com.falaai.JSON;

/**
 * RiskAuditDetectionsV2
 */
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.25.0")
public class RiskAuditDetectionsV2 {
  public static final String SERIALIZED_NAME_VIOLATIONS = "violations";
  @SerializedName(SERIALIZED_NAME_VIOLATIONS)
  @jakarta.annotation.Nullable
  private List<RiskAuditDetectionItemV2> violations = new ArrayList<>();

  public static final String SERIALIZED_NAME_POSITIVES = "positives";
  @SerializedName(SERIALIZED_NAME_POSITIVES)
  @jakarta.annotation.Nullable
  private List<RiskAuditDetectionItemV2> positives = new ArrayList<>();

  public static final String SERIALIZED_NAME_CLIENT_RISK_ALERTS = "client_risk_alerts";
  @SerializedName(SERIALIZED_NAME_CLIENT_RISK_ALERTS)
  @jakarta.annotation.Nullable
  private List<Map<String, Object>> clientRiskAlerts = new ArrayList<>();

  public static final String SERIALIZED_NAME_CLIENT_BEHAVIOR_ALERTS = "client_behavior_alerts";
  @SerializedName(SERIALIZED_NAME_CLIENT_BEHAVIOR_ALERTS)
  @jakarta.annotation.Nullable
  private List<Map<String, Object>> clientBehaviorAlerts = new ArrayList<>();

  public static final String SERIALIZED_NAME_CLIENT_NEGATIVES = "client_negatives";
  @SerializedName(SERIALIZED_NAME_CLIENT_NEGATIVES)
  @jakarta.annotation.Nullable
  private List<RiskAuditDetectionItemV2> clientNegatives = new ArrayList<>();

  public RiskAuditDetectionsV2() {
  }

  public RiskAuditDetectionsV2 violations(@jakarta.annotation.Nullable List<RiskAuditDetectionItemV2> violations) {
    this.violations = violations;
    return this;
  }

  public RiskAuditDetectionsV2 addViolationsItem(RiskAuditDetectionItemV2 violationsItem) {
    if (this.violations == null) {
      this.violations = new ArrayList<>();
    }
    this.violations.add(violationsItem);
    return this;
  }

  /**
   * Active violations
   * @return violations
   */
  @jakarta.annotation.Nullable
  public List<RiskAuditDetectionItemV2> getViolations() {
    return violations;
  }

  public void setViolations(@jakarta.annotation.Nullable List<RiskAuditDetectionItemV2> violations) {
    this.violations = violations;
  }


  public RiskAuditDetectionsV2 positives(@jakarta.annotation.Nullable List<RiskAuditDetectionItemV2> positives) {
    this.positives = positives;
    return this;
  }

  public RiskAuditDetectionsV2 addPositivesItem(RiskAuditDetectionItemV2 positivesItem) {
    if (this.positives == null) {
      this.positives = new ArrayList<>();
    }
    this.positives.add(positivesItem);
    return this;
  }

  /**
   * Active positives
   * @return positives
   */
  @jakarta.annotation.Nullable
  public List<RiskAuditDetectionItemV2> getPositives() {
    return positives;
  }

  public void setPositives(@jakarta.annotation.Nullable List<RiskAuditDetectionItemV2> positives) {
    this.positives = positives;
  }


  public RiskAuditDetectionsV2 clientRiskAlerts(@jakarta.annotation.Nullable List<Map<String, Object>> clientRiskAlerts) {
    this.clientRiskAlerts = clientRiskAlerts;
    return this;
  }

  public RiskAuditDetectionsV2 addClientRiskAlertsItem(Map<String, Object> clientRiskAlertsItem) {
    if (this.clientRiskAlerts == null) {
      this.clientRiskAlerts = new ArrayList<>();
    }
    this.clientRiskAlerts.add(clientRiskAlertsItem);
    return this;
  }

  /**
   * Client risk alerts
   * @return clientRiskAlerts
   */
  @jakarta.annotation.Nullable
  public List<Map<String, Object>> getClientRiskAlerts() {
    return clientRiskAlerts;
  }

  public void setClientRiskAlerts(@jakarta.annotation.Nullable List<Map<String, Object>> clientRiskAlerts) {
    this.clientRiskAlerts = clientRiskAlerts;
  }


  public RiskAuditDetectionsV2 clientBehaviorAlerts(@jakarta.annotation.Nullable List<Map<String, Object>> clientBehaviorAlerts) {
    this.clientBehaviorAlerts = clientBehaviorAlerts;
    return this;
  }

  public RiskAuditDetectionsV2 addClientBehaviorAlertsItem(Map<String, Object> clientBehaviorAlertsItem) {
    if (this.clientBehaviorAlerts == null) {
      this.clientBehaviorAlerts = new ArrayList<>();
    }
    this.clientBehaviorAlerts.add(clientBehaviorAlertsItem);
    return this;
  }

  /**
   * Client behavior alerts
   * @return clientBehaviorAlerts
   */
  @jakarta.annotation.Nullable
  public List<Map<String, Object>> getClientBehaviorAlerts() {
    return clientBehaviorAlerts;
  }

  public void setClientBehaviorAlerts(@jakarta.annotation.Nullable List<Map<String, Object>> clientBehaviorAlerts) {
    this.clientBehaviorAlerts = clientBehaviorAlerts;
  }


  public RiskAuditDetectionsV2 clientNegatives(@jakarta.annotation.Nullable List<RiskAuditDetectionItemV2> clientNegatives) {
    this.clientNegatives = clientNegatives;
    return this;
  }

  public RiskAuditDetectionsV2 addClientNegativesItem(RiskAuditDetectionItemV2 clientNegativesItem) {
    if (this.clientNegatives == null) {
      this.clientNegatives = new ArrayList<>();
    }
    this.clientNegatives.add(clientNegativesItem);
    return this;
  }

  /**
   * Client negatives
   * @return clientNegatives
   */
  @jakarta.annotation.Nullable
  public List<RiskAuditDetectionItemV2> getClientNegatives() {
    return clientNegatives;
  }

  public void setClientNegatives(@jakarta.annotation.Nullable List<RiskAuditDetectionItemV2> clientNegatives) {
    this.clientNegatives = clientNegatives;
  }

  /**
   * A container for additional, undeclared properties.
   * This is a holder for any undeclared properties as specified with
   * the 'additionalProperties' keyword in the OAS document.
   */
  private Map<String, Object> additionalProperties;

  /**
   * Set the additional (undeclared) property with the specified name and value.
   * If the property does not already exist, create it otherwise replace it.
   *
   * @param key name of the property
   * @param value value of the property
   * @return the RiskAuditDetectionsV2 instance itself
   */
  public RiskAuditDetectionsV2 putAdditionalProperty(String key, Object value) {
    if (this.additionalProperties == null) {
        this.additionalProperties = new HashMap<String, Object>();
    }
    this.additionalProperties.put(key, value);
    return this;
  }

  /**
   * Return the additional (undeclared) property.
   *
   * @return a map of objects
   */
  public Map<String, Object> getAdditionalProperties() {
    return additionalProperties;
  }

  /**
   * Return the additional (undeclared) property with the specified name.
   *
   * @param key name of the property
   * @return an object
   */
  public Object getAdditionalProperty(String key) {
    if (this.additionalProperties == null) {
        return null;
    }
    return this.additionalProperties.get(key);
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RiskAuditDetectionsV2 riskAuditDetectionsV2 = (RiskAuditDetectionsV2) o;
    return Objects.equals(this.violations, riskAuditDetectionsV2.violations) &&
        Objects.equals(this.positives, riskAuditDetectionsV2.positives) &&
        Objects.equals(this.clientRiskAlerts, riskAuditDetectionsV2.clientRiskAlerts) &&
        Objects.equals(this.clientBehaviorAlerts, riskAuditDetectionsV2.clientBehaviorAlerts) &&
        Objects.equals(this.clientNegatives, riskAuditDetectionsV2.clientNegatives)&&
        Objects.equals(this.additionalProperties, riskAuditDetectionsV2.additionalProperties);
  }

  @Override
  public int hashCode() {
    return Objects.hash(violations, positives, clientRiskAlerts, clientBehaviorAlerts, clientNegatives, additionalProperties);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RiskAuditDetectionsV2 {\n");
    sb.append("    violations: ").append(toIndentedString(violations)).append("\n");
    sb.append("    positives: ").append(toIndentedString(positives)).append("\n");
    sb.append("    clientRiskAlerts: ").append(toIndentedString(clientRiskAlerts)).append("\n");
    sb.append("    clientBehaviorAlerts: ").append(toIndentedString(clientBehaviorAlerts)).append("\n");
    sb.append("    clientNegatives: ").append(toIndentedString(clientNegatives)).append("\n");
    sb.append("    additionalProperties: ").append(toIndentedString(additionalProperties)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("violations", "positives", "client_risk_alerts", "client_behavior_alerts", "client_negatives"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(0);
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to RiskAuditDetectionsV2
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!RiskAuditDetectionsV2.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field(s) %s in RiskAuditDetectionsV2 is not found in the empty JSON string", RiskAuditDetectionsV2.openapiRequiredFields.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if (jsonObj.get("violations") != null && !jsonObj.get("violations").isJsonNull()) {
        JsonArray jsonArrayviolations = jsonObj.getAsJsonArray("violations");
        if (jsonArrayviolations != null) {
          // ensure the json data is an array
          if (!jsonObj.get("violations").isJsonArray()) {
            throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `violations` to be an array in the JSON string but got `%s`", jsonObj.get("violations").toString()));
          }

          // validate the optional field `violations` (array)
          for (int i = 0; i < jsonArrayviolations.size(); i++) {
            RiskAuditDetectionItemV2.validateJsonElement(jsonArrayviolations.get(i));
          };
        }
      }
      if (jsonObj.get("positives") != null && !jsonObj.get("positives").isJsonNull()) {
        JsonArray jsonArraypositives = jsonObj.getAsJsonArray("positives");
        if (jsonArraypositives != null) {
          // ensure the json data is an array
          if (!jsonObj.get("positives").isJsonArray()) {
            throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `positives` to be an array in the JSON string but got `%s`", jsonObj.get("positives").toString()));
          }

          // validate the optional field `positives` (array)
          for (int i = 0; i < jsonArraypositives.size(); i++) {
            RiskAuditDetectionItemV2.validateJsonElement(jsonArraypositives.get(i));
          };
        }
      }
      // ensure the optional json data is an array if present
      if (jsonObj.get("client_risk_alerts") != null && !jsonObj.get("client_risk_alerts").isJsonNull() && !jsonObj.get("client_risk_alerts").isJsonArray()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `client_risk_alerts` to be an array in the JSON string but got `%s`", jsonObj.get("client_risk_alerts").toString()));
      }
      // ensure the optional json data is an array if present
      if (jsonObj.get("client_behavior_alerts") != null && !jsonObj.get("client_behavior_alerts").isJsonNull() && !jsonObj.get("client_behavior_alerts").isJsonArray()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `client_behavior_alerts` to be an array in the JSON string but got `%s`", jsonObj.get("client_behavior_alerts").toString()));
      }
      if (jsonObj.get("client_negatives") != null && !jsonObj.get("client_negatives").isJsonNull()) {
        JsonArray jsonArrayclientNegatives = jsonObj.getAsJsonArray("client_negatives");
        if (jsonArrayclientNegatives != null) {
          // ensure the json data is an array
          if (!jsonObj.get("client_negatives").isJsonArray()) {
            throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `client_negatives` to be an array in the JSON string but got `%s`", jsonObj.get("client_negatives").toString()));
          }

          // validate the optional field `client_negatives` (array)
          for (int i = 0; i < jsonArrayclientNegatives.size(); i++) {
            RiskAuditDetectionItemV2.validateJsonElement(jsonArrayclientNegatives.get(i));
          };
        }
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!RiskAuditDetectionsV2.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'RiskAuditDetectionsV2' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<RiskAuditDetectionsV2> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(RiskAuditDetectionsV2.class));

       return (TypeAdapter<T>) new TypeAdapter<RiskAuditDetectionsV2>() {
           @Override
           public void write(JsonWriter out, RiskAuditDetectionsV2 value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             obj.remove("additionalProperties");
             // serialize additional properties
             if (value.getAdditionalProperties() != null) {
               for (Map.Entry<String, Object> entry : value.getAdditionalProperties().entrySet()) {
                 if (entry.getValue() instanceof String)
                   obj.addProperty(entry.getKey(), (String) entry.getValue());
                 else if (entry.getValue() instanceof Number)
                   obj.addProperty(entry.getKey(), (Number) entry.getValue());
                 else if (entry.getValue() instanceof Boolean)
                   obj.addProperty(entry.getKey(), (Boolean) entry.getValue());
                 else if (entry.getValue() instanceof Character)
                   obj.addProperty(entry.getKey(), (Character) entry.getValue());
                 else {
                   JsonElement jsonElement = gson.toJsonTree(entry.getValue());
                   if (jsonElement.isJsonNull()) {
                     obj.add(entry.getKey(), JsonNull.INSTANCE);
                   } else if (jsonElement.isJsonArray()) {
                     obj.add(entry.getKey(), jsonElement.getAsJsonArray());
                   } else {
                     obj.add(entry.getKey(), jsonElement.getAsJsonObject());
                   }
                 }
               }
             }
             elementAdapter.write(out, obj);
           }

           @Override
           public RiskAuditDetectionsV2 read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             JsonObject jsonObj = jsonElement.getAsJsonObject();
             // store additional fields in the deserialized instance
             RiskAuditDetectionsV2 instance = thisAdapter.fromJsonTree(jsonObj);
             for (Map.Entry<String, JsonElement> entry : jsonObj.entrySet()) {
               if (!openapiFields.contains(entry.getKey())) {
                 if (entry.getValue().isJsonPrimitive()) { // primitive type
                   if (entry.getValue().getAsJsonPrimitive().isString())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsString());
                   else if (entry.getValue().getAsJsonPrimitive().isNumber())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsNumber());
                   else if (entry.getValue().getAsJsonPrimitive().isBoolean())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsBoolean());
                   else
                     throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The field `%s` has unknown primitive type. Value: %s", entry.getKey(), entry.getValue().toString()));
                 } else if (entry.getValue().isJsonArray()) {
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), List.class));
                 } else { // JSON object
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), HashMap.class));
                 }
               }
             }
             return instance;
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of RiskAuditDetectionsV2 given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of RiskAuditDetectionsV2
   * @throws IOException if the JSON string is invalid with respect to RiskAuditDetectionsV2
   */
  public static RiskAuditDetectionsV2 fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, RiskAuditDetectionsV2.class);
  }

  /**
   * Convert an instance of RiskAuditDetectionsV2 to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

