/*
 * FalaAI API
 * Transcribe, diagnose and score calls with 3 simple endpoints.  **Endpoints:** - `POST /v1/audio/transcriptions` — Audio to text - `POST /v1/analyze/diagnostic` — Conversation analysis - `POST /v1/analyze/auditoriaRisco` — Compliance audit  **Complete flow (Python):** ```python import httpx  API = 'https://api.fala.ai' KEY = 'fai_xxx' HD = {'Authorization': f'Bearer {KEY}'}  # 1. Transcribe files = {'file': open('call.mp3', 'rb')} resp = httpx.post(f'{API}/v1/audio/transcriptions', headers=HD, files=files, data={'model': 'falaai-transcribe-1', 'language': 'pt'}) tr = resp.json() print(f'Text: {tr[\"text\"][:100]}...')  # 2. Diagnose resp = httpx.post(f'{API}/v1/analyze/diagnostic', headers=HD, json={'dialog': tr['dialog'], 'language': 'pt-BR', 'duration_seconds': tr['duration_seconds']}) diag = resp.json() print(f'Sentiment: {diag[\"analysis\"][\"sentiment\"][\"list_choice\"]}') print(f'Summary: {diag[\"analysis\"][\"dialogue_summary\"][\"explanation\"][:100]}...')  # 3. Audit resp = httpx.post(f'{API}/v1/analyze/auditoriaRisco', headers=HD, json={'dialogo': tr['dialog'], 'duration_seconds': tr['duration_seconds']}) audit = resp.json() print(f'Score: {audit[\"audit_score\"]} | Verdict: {audit[\"verdict\"]}') print(f'Detections: {audit[\"total_detections\"]} | Violations: {len(audit[\"violations\"])} | Positives: {len(audit[\"positives\"])}') ```  **Authentication:** All endpoints require an API Key in the `Authorization` header: `Bearer fai_xxx`  Get your API Key at [falaai.action.tec.br/api](https://falaai.action.tec.br/api)
 *
 * The version of the OpenAPI document: 1.21.47
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.falaai.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonNull;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import com.falaai.JSON;

/**
 * WebhookItem
 */
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.25.0")
public class WebhookItem {
  public static final String SERIALIZED_NAME_ID = "id";
  @SerializedName(SERIALIZED_NAME_ID)
  @jakarta.annotation.Nonnull
  private String id;

  public static final String SERIALIZED_NAME_USER_ID = "user_id";
  @SerializedName(SERIALIZED_NAME_USER_ID)
  @jakarta.annotation.Nonnull
  private String userId;

  public static final String SERIALIZED_NAME_NAME = "name";
  @SerializedName(SERIALIZED_NAME_NAME)
  @jakarta.annotation.Nonnull
  private String name;

  public static final String SERIALIZED_NAME_URL = "url";
  @SerializedName(SERIALIZED_NAME_URL)
  @jakarta.annotation.Nonnull
  private String url;

  public static final String SERIALIZED_NAME_SECRET = "secret";
  @SerializedName(SERIALIZED_NAME_SECRET)
  @jakarta.annotation.Nonnull
  private String secret;

  public static final String SERIALIZED_NAME_EVENTS = "events";
  @SerializedName(SERIALIZED_NAME_EVENTS)
  @jakarta.annotation.Nonnull
  private List<String> events = new ArrayList<>();

  public static final String SERIALIZED_NAME_ACTIVE = "active";
  @SerializedName(SERIALIZED_NAME_ACTIVE)
  @jakarta.annotation.Nonnull
  private Boolean active;

  public static final String SERIALIZED_NAME_RETRY_ENABLED = "retry_enabled";
  @SerializedName(SERIALIZED_NAME_RETRY_ENABLED)
  @jakarta.annotation.Nonnull
  private Boolean retryEnabled;

  public static final String SERIALIZED_NAME_LAST_DELIVERY_AT = "last_delivery_at";
  @SerializedName(SERIALIZED_NAME_LAST_DELIVERY_AT)
  @jakarta.annotation.Nullable
  private String lastDeliveryAt;

  public static final String SERIALIZED_NAME_LAST_STATUS = "last_status";
  @SerializedName(SERIALIZED_NAME_LAST_STATUS)
  @jakarta.annotation.Nullable
  private Integer lastStatus;

  public static final String SERIALIZED_NAME_FAILURE_COUNT = "failure_count";
  @SerializedName(SERIALIZED_NAME_FAILURE_COUNT)
  @jakarta.annotation.Nullable
  private Integer failureCount = 0;

  public static final String SERIALIZED_NAME_CREATED_AT = "created_at";
  @SerializedName(SERIALIZED_NAME_CREATED_AT)
  @jakarta.annotation.Nonnull
  private String createdAt;

  public static final String SERIALIZED_NAME_UPDATED_AT = "updated_at";
  @SerializedName(SERIALIZED_NAME_UPDATED_AT)
  @jakarta.annotation.Nonnull
  private String updatedAt;

  public WebhookItem() {
  }

  public WebhookItem id(@jakarta.annotation.Nonnull String id) {
    this.id = id;
    return this;
  }

  /**
   * Webhook id
   * @return id
   */
  @jakarta.annotation.Nonnull
  public String getId() {
    return id;
  }

  public void setId(@jakarta.annotation.Nonnull String id) {
    this.id = id;
  }


  public WebhookItem userId(@jakarta.annotation.Nonnull String userId) {
    this.userId = userId;
    return this;
  }

  /**
   * Owner user id
   * @return userId
   */
  @jakarta.annotation.Nonnull
  public String getUserId() {
    return userId;
  }

  public void setUserId(@jakarta.annotation.Nonnull String userId) {
    this.userId = userId;
  }


  public WebhookItem name(@jakarta.annotation.Nonnull String name) {
    this.name = name;
    return this;
  }

  /**
   * Webhook name
   * @return name
   */
  @jakarta.annotation.Nonnull
  public String getName() {
    return name;
  }

  public void setName(@jakarta.annotation.Nonnull String name) {
    this.name = name;
  }


  public WebhookItem url(@jakarta.annotation.Nonnull String url) {
    this.url = url;
    return this;
  }

  /**
   * Destination URL
   * @return url
   */
  @jakarta.annotation.Nonnull
  public String getUrl() {
    return url;
  }

  public void setUrl(@jakarta.annotation.Nonnull String url) {
    this.url = url;
  }


  public WebhookItem secret(@jakarta.annotation.Nonnull String secret) {
    this.secret = secret;
    return this;
  }

  /**
   * HMAC signing secret
   * @return secret
   */
  @jakarta.annotation.Nonnull
  public String getSecret() {
    return secret;
  }

  public void setSecret(@jakarta.annotation.Nonnull String secret) {
    this.secret = secret;
  }


  public WebhookItem events(@jakarta.annotation.Nonnull List<String> events) {
    this.events = events;
    return this;
  }

  public WebhookItem addEventsItem(String eventsItem) {
    if (this.events == null) {
      this.events = new ArrayList<>();
    }
    this.events.add(eventsItem);
    return this;
  }

  /**
   * Subscribed events
   * @return events
   */
  @jakarta.annotation.Nonnull
  public List<String> getEvents() {
    return events;
  }

  public void setEvents(@jakarta.annotation.Nonnull List<String> events) {
    this.events = events;
  }


  public WebhookItem active(@jakarta.annotation.Nonnull Boolean active) {
    this.active = active;
    return this;
  }

  /**
   * Is active
   * @return active
   */
  @jakarta.annotation.Nonnull
  public Boolean getActive() {
    return active;
  }

  public void setActive(@jakarta.annotation.Nonnull Boolean active) {
    this.active = active;
  }


  public WebhookItem retryEnabled(@jakarta.annotation.Nonnull Boolean retryEnabled) {
    this.retryEnabled = retryEnabled;
    return this;
  }

  /**
   * Retry enabled
   * @return retryEnabled
   */
  @jakarta.annotation.Nonnull
  public Boolean getRetryEnabled() {
    return retryEnabled;
  }

  public void setRetryEnabled(@jakarta.annotation.Nonnull Boolean retryEnabled) {
    this.retryEnabled = retryEnabled;
  }


  public WebhookItem lastDeliveryAt(@jakarta.annotation.Nullable String lastDeliveryAt) {
    this.lastDeliveryAt = lastDeliveryAt;
    return this;
  }

  /**
   * ISO 8601 of last delivery
   * @return lastDeliveryAt
   */
  @jakarta.annotation.Nullable
  public String getLastDeliveryAt() {
    return lastDeliveryAt;
  }

  public void setLastDeliveryAt(@jakarta.annotation.Nullable String lastDeliveryAt) {
    this.lastDeliveryAt = lastDeliveryAt;
  }


  public WebhookItem lastStatus(@jakarta.annotation.Nullable Integer lastStatus) {
    this.lastStatus = lastStatus;
    return this;
  }

  /**
   * Last HTTP status delivered
   * @return lastStatus
   */
  @jakarta.annotation.Nullable
  public Integer getLastStatus() {
    return lastStatus;
  }

  public void setLastStatus(@jakarta.annotation.Nullable Integer lastStatus) {
    this.lastStatus = lastStatus;
  }


  public WebhookItem failureCount(@jakarta.annotation.Nullable Integer failureCount) {
    this.failureCount = failureCount;
    return this;
  }

  /**
   * Consecutive failures
   * @return failureCount
   */
  @jakarta.annotation.Nullable
  public Integer getFailureCount() {
    return failureCount;
  }

  public void setFailureCount(@jakarta.annotation.Nullable Integer failureCount) {
    this.failureCount = failureCount;
  }


  public WebhookItem createdAt(@jakarta.annotation.Nonnull String createdAt) {
    this.createdAt = createdAt;
    return this;
  }

  /**
   * ISO 8601 created
   * @return createdAt
   */
  @jakarta.annotation.Nonnull
  public String getCreatedAt() {
    return createdAt;
  }

  public void setCreatedAt(@jakarta.annotation.Nonnull String createdAt) {
    this.createdAt = createdAt;
  }


  public WebhookItem updatedAt(@jakarta.annotation.Nonnull String updatedAt) {
    this.updatedAt = updatedAt;
    return this;
  }

  /**
   * ISO 8601 updated
   * @return updatedAt
   */
  @jakarta.annotation.Nonnull
  public String getUpdatedAt() {
    return updatedAt;
  }

  public void setUpdatedAt(@jakarta.annotation.Nonnull String updatedAt) {
    this.updatedAt = updatedAt;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    WebhookItem webhookItem = (WebhookItem) o;
    return Objects.equals(this.id, webhookItem.id) &&
        Objects.equals(this.userId, webhookItem.userId) &&
        Objects.equals(this.name, webhookItem.name) &&
        Objects.equals(this.url, webhookItem.url) &&
        Objects.equals(this.secret, webhookItem.secret) &&
        Objects.equals(this.events, webhookItem.events) &&
        Objects.equals(this.active, webhookItem.active) &&
        Objects.equals(this.retryEnabled, webhookItem.retryEnabled) &&
        Objects.equals(this.lastDeliveryAt, webhookItem.lastDeliveryAt) &&
        Objects.equals(this.lastStatus, webhookItem.lastStatus) &&
        Objects.equals(this.failureCount, webhookItem.failureCount) &&
        Objects.equals(this.createdAt, webhookItem.createdAt) &&
        Objects.equals(this.updatedAt, webhookItem.updatedAt);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, userId, name, url, secret, events, active, retryEnabled, lastDeliveryAt, lastStatus, failureCount, createdAt, updatedAt);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class WebhookItem {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    userId: ").append(toIndentedString(userId)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    url: ").append(toIndentedString(url)).append("\n");
    sb.append("    secret: ").append(toIndentedString(secret)).append("\n");
    sb.append("    events: ").append(toIndentedString(events)).append("\n");
    sb.append("    active: ").append(toIndentedString(active)).append("\n");
    sb.append("    retryEnabled: ").append(toIndentedString(retryEnabled)).append("\n");
    sb.append("    lastDeliveryAt: ").append(toIndentedString(lastDeliveryAt)).append("\n");
    sb.append("    lastStatus: ").append(toIndentedString(lastStatus)).append("\n");
    sb.append("    failureCount: ").append(toIndentedString(failureCount)).append("\n");
    sb.append("    createdAt: ").append(toIndentedString(createdAt)).append("\n");
    sb.append("    updatedAt: ").append(toIndentedString(updatedAt)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("id", "user_id", "name", "url", "secret", "events", "active", "retry_enabled", "last_delivery_at", "last_status", "failure_count", "created_at", "updated_at"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(Arrays.asList("id", "user_id", "name", "url", "secret", "events", "active", "retry_enabled", "created_at", "updated_at"));
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to WebhookItem
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!WebhookItem.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field(s) %s in WebhookItem is not found in the empty JSON string", WebhookItem.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!WebhookItem.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The field `%s` in the JSON string is not defined in the `WebhookItem` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : WebhookItem.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if (!jsonObj.get("id").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `id` to be a primitive type in the JSON string but got `%s`", jsonObj.get("id").toString()));
      }
      if (!jsonObj.get("user_id").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `user_id` to be a primitive type in the JSON string but got `%s`", jsonObj.get("user_id").toString()));
      }
      if (!jsonObj.get("name").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `name` to be a primitive type in the JSON string but got `%s`", jsonObj.get("name").toString()));
      }
      if (!jsonObj.get("url").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `url` to be a primitive type in the JSON string but got `%s`", jsonObj.get("url").toString()));
      }
      if (!jsonObj.get("secret").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `secret` to be a primitive type in the JSON string but got `%s`", jsonObj.get("secret").toString()));
      }
      // ensure the required json array is present
      if (jsonObj.get("events") == null) {
        throw new IllegalArgumentException("Expected the field `linkedContent` to be an array in the JSON string but got `null`");
      } else if (!jsonObj.get("events").isJsonArray()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `events` to be an array in the JSON string but got `%s`", jsonObj.get("events").toString()));
      }
      if ((jsonObj.get("last_delivery_at") != null && !jsonObj.get("last_delivery_at").isJsonNull()) && !jsonObj.get("last_delivery_at").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `last_delivery_at` to be a primitive type in the JSON string but got `%s`", jsonObj.get("last_delivery_at").toString()));
      }
      if (!jsonObj.get("created_at").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `created_at` to be a primitive type in the JSON string but got `%s`", jsonObj.get("created_at").toString()));
      }
      if (!jsonObj.get("updated_at").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `updated_at` to be a primitive type in the JSON string but got `%s`", jsonObj.get("updated_at").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!WebhookItem.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'WebhookItem' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<WebhookItem> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(WebhookItem.class));

       return (TypeAdapter<T>) new TypeAdapter<WebhookItem>() {
           @Override
           public void write(JsonWriter out, WebhookItem value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public WebhookItem read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of WebhookItem given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of WebhookItem
   * @throws IOException if the JSON string is invalid with respect to WebhookItem
   */
  public static WebhookItem fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, WebhookItem.class);
  }

  /**
   * Convert an instance of WebhookItem to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

