/*
 * FalaAI API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.21.49
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.falaai.api;

import com.falaai.ApiException;
import com.falaai.model.CreateEmailAlertRequest;
import com.falaai.model.EmailAlertItem;
import com.falaai.model.EmailAlertListResponse;
import com.falaai.model.EmailAlertMessageResponse;
import com.falaai.model.HTTPValidationError;
import com.falaai.model.UpdateEmailAlertRequest;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for EmailAlertsApi
 */
@Disabled
public class EmailAlertsApiTest {

    private final EmailAlertsApi api = new EmailAlertsApi();

    /**
     * Create email alert
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void createEmailAlertV1EmailAlertsPostTest() throws ApiException {
        CreateEmailAlertRequest createEmailAlertRequest = null;
        EmailAlertItem response = api.createEmailAlertV1EmailAlertsPost(createEmailAlertRequest);
        // TODO: test validations
    }

    /**
     * Delete email alert
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void deleteEmailAlertV1EmailAlertsAlertIdDeleteTest() throws ApiException {
        String alertId = null;
        EmailAlertMessageResponse response = api.deleteEmailAlertV1EmailAlertsAlertIdDelete(alertId);
        // TODO: test validations
    }

    /**
     * List email alerts
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void listEmailAlertsV1EmailAlertsGetTest() throws ApiException {
        Integer page = null;
        Integer limit = null;
        EmailAlertListResponse response = api.listEmailAlertsV1EmailAlertsGet(page, limit);
        // TODO: test validations
    }

    /**
     * Update email alert
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void updateEmailAlertV1EmailAlertsAlertIdPutTest() throws ApiException {
        String alertId = null;
        UpdateEmailAlertRequest updateEmailAlertRequest = null;
        EmailAlertMessageResponse response = api.updateEmailAlertV1EmailAlertsAlertIdPut(alertId, updateEmailAlertRequest);
        // TODO: test validations
    }

}
