/*
 * FalaAI API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.21.49
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.falaai.api;

import com.falaai.ApiException;
import java.io.File;
import com.falaai.model.HTTPValidationError;
import com.falaai.model.TranscriptionResponse;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for SpeechApi
 */
@Disabled
public class SpeechApiTest {

    private final SpeechApi api = new SpeechApi();

    /**
     * Transcribe audio to text
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void createTranscriptionV1AudioTranscriptionsPostTest() throws ApiException {
        File _file = null;
        String model = null;
        String language = null;
        String clientReferenceId = null;
        TranscriptionResponse response = api.createTranscriptionV1AudioTranscriptionsPost(_file, model, language, clientReferenceId);
        // TODO: test validations
    }

}
