/*
 * FalaAI API
 * Transcribe, diagnose and score calls with 3 simple endpoints.  **Endpoints:** - `POST /v1/audio/transcriptions` — Audio to text - `POST /v1/analyze/diagnostic` — Conversation analysis - `POST /v1/analyze/auditoriaRisco` — Compliance audit  **Complete flow (Python):** ```python import httpx  API = 'https://api01-falaai.action.tec.br' KEY = 'fai_xxx' HD = {'Authorization': f'Bearer {KEY}'}  # 1. Transcribe files = {'file': open('call.mp3', 'rb')} resp = httpx.post(f'{API}/v1/audio/transcriptions', headers=HD, files=files, data={'model': 'falaai-transcribe-1', 'language': 'pt'}) tr = resp.json() print(f'Text: {tr[\"text\"][:100]}...')  # 2. Diagnose resp = httpx.post(f'{API}/v1/analyze/diagnostic', headers=HD, json={'dialog': tr['dialog'], 'language': 'pt-BR', 'duration_seconds': tr['duration_seconds']}) diag = resp.json() print(f'Sentiment: {diag[\"analysis\"][\"sentiment\"][\"list_choice\"]}') print(f'Summary: {diag[\"analysis\"][\"dialogue_summary\"][\"explanation\"][:100]}...')  # 3. Audit resp = httpx.post(f'{API}/v1/analyze/auditoriaRisco', headers=HD, json={'dialogo': tr['dialog'], 'duration_seconds': tr['duration_seconds']}) audit = resp.json() print(f'Score: {audit[\"audit_score\"]} | Verdict: {audit[\"verdict\"]}') print(f'Detections: {audit[\"total_detections\"]} | Violations: {len(audit[\"violations\"])} | Positives: {len(audit[\"positives\"])}') ```  **Authentication:** All endpoints require an API Key in the `Authorization` header: `Bearer fai_xxx`  Get your API Key at [falaai.action.tec.br/api](https://falaai.action.tec.br/api)
 *
 * The version of the OpenAPI document: 1.21.47
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.falaai.api;

import com.falaai.ApiException;
import java.io.File;
import com.falaai.model.HTTPValidationError;
import com.falaai.model.TranscriptionResponse;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for SpeechApi
 */
@Disabled
public class SpeechApiTest {

    private final SpeechApi api = new SpeechApi();

    /**
     * Transcribe audio to text
     *
     * Upload an audio file and receive transcription with speaker diarization, audio events, and dialog.  **Supported formats:** .mp3, .mp4, .m4a, .wav, .flac, .ogg, .webm, .aac, .opus  **Limits:** - Maximum audio duration: 3 hours - Maximum file size: 1GB - Cost: 1 credit per second of audio (rounded up), minimum 1 credit  **Supported languages:** pt, en, es, fr, de, it, ja, ko, nl, pl, ru, tr, zh, vi, id, th, ar, hi, cs, da, el, fi, he, hu, ms, no, ro, sk, sv, ta, uk  **Python:** &#x60;&#x60;&#x60;python import httpx  response &#x3D; httpx.post(     &#39;https://api01-falaai.action.tec.br/v1/audio/transcriptions&#39;,     headers&#x3D;{&#39;Authorization&#39;: &#39;Bearer fai_xxx&#39;},     files&#x3D;{&#39;file&#39;: open(&#39;call.mp3&#39;, &#39;rb&#39;)},     data&#x3D;{&#39;model&#39;: &#39;falaai-transcribe-1&#39;, &#39;language&#39;: &#39;pt&#39;} ) print(response.json()) &#x60;&#x60;&#x60;  **cURL:** &#x60;&#x60;&#x60;bash curl https://api01-falaai.action.tec.br/v1/audio/transcriptions \\   -H &#39;Authorization: Bearer fai_xxx&#39; \\   -F &#39;file&#x3D;@call.mp3&#39; \\   -F &#39;model&#x3D;falaai-transcribe-1&#39; \\   -F &#39;language&#x3D;pt&#39; &#x60;&#x60;&#x60;
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void createTranscriptionV1AudioTranscriptionsPostTest() throws ApiException {
        File _file = null;
        String model = null;
        String language = null;
        String clientReferenceId = null;
        TranscriptionResponse response = api.createTranscriptionV1AudioTranscriptionsPost(_file, model, language, clientReferenceId);
        // TODO: test validations
    }

}
