/*
 * FalaAI API
 * Transcribe, diagnose and score calls with 3 simple endpoints.  **Endpoints:** - `POST /v1/audio/transcriptions` — Audio to text - `POST /v1/analyze/diagnostic` — Conversation analysis - `POST /v1/analyze/auditoriaRisco` — Compliance audit  **Complete flow (Python):** ```python import httpx  API = 'https://api.fala.ai' KEY = 'fai_xxx' HD = {'Authorization': f'Bearer {KEY}'}  # 1. Transcribe files = {'file': open('call.mp3', 'rb')} resp = httpx.post(f'{API}/v1/audio/transcriptions', headers=HD, files=files, data={'model': 'falaai-transcribe-1', 'language': 'pt'}) tr = resp.json() print(f'Text: {tr[\"text\"][:100]}...')  # 2. Diagnose resp = httpx.post(f'{API}/v1/analyze/diagnostic', headers=HD, json={'dialog': tr['dialog'], 'language': 'pt-BR', 'duration_seconds': tr['duration_seconds']}) diag = resp.json() print(f'Sentiment: {diag[\"analysis\"][\"sentiment\"][\"list_choice\"]}') print(f'Summary: {diag[\"analysis\"][\"dialogue_summary\"][\"explanation\"][:100]}...')  # 3. Audit resp = httpx.post(f'{API}/v1/analyze/auditoriaRisco', headers=HD, json={'dialogo': tr['dialog'], 'duration_seconds': tr['duration_seconds']}) audit = resp.json() print(f'Score: {audit[\"audit_score\"]} | Verdict: {audit[\"verdict\"]}') print(f'Detections: {audit[\"total_detections\"]} | Violations: {len(audit[\"violations\"])} | Positives: {len(audit[\"positives\"])}') ```  **Authentication:** All endpoints require an API Key in the `Authorization` header: `Bearer fai_xxx`  Get your API Key at [falaai.action.tec.br/api](https://falaai.action.tec.br/api)
 *
 * The version of the OpenAPI document: 1.21.47
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.falaai.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.openapitools.jackson.nullable.JsonNullable;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for AuditoriaRiscoSummaryV2
 */
public class AuditoriaRiscoSummaryV2Test {
    private final AuditoriaRiscoSummaryV2 model = new AuditoriaRiscoSummaryV2();

    /**
     * Model tests for AuditoriaRiscoSummaryV2
     */
    @Test
    public void testAuditoriaRiscoSummaryV2() {
        // TODO: test AuditoriaRiscoSummaryV2
    }

    /**
     * Test the property 'totalTurns'
     */
    @Test
    public void totalTurnsTest() {
        // TODO: test totalTurns
    }

    /**
     * Test the property 'totalCalibrated'
     */
    @Test
    public void totalCalibratedTest() {
        // TODO: test totalCalibrated
    }

    /**
     * Test the property 'active'
     */
    @Test
    public void activeTest() {
        // TODO: test active
    }

    /**
     * Test the property 'tolerated'
     */
    @Test
    public void toleratedTest() {
        // TODO: test tolerated
    }

    /**
     * Test the property 'blocked'
     */
    @Test
    public void blockedTest() {
        // TODO: test blocked
    }

    /**
     * Test the property 'audioEventsUsed'
     */
    @Test
    public void audioEventsUsedTest() {
        // TODO: test audioEventsUsed
    }

    /**
     * Test the property 'audioEventsAggravated'
     */
    @Test
    public void audioEventsAggravatedTest() {
        // TODO: test audioEventsAggravated
    }

    /**
     * Test the property 'macAudioApplied'
     */
    @Test
    public void macAudioAppliedTest() {
        // TODO: test macAudioApplied
    }

    /**
     * Test the property 'mvadApplied'
     */
    @Test
    public void mvadAppliedTest() {
        // TODO: test mvadApplied
    }

    /**
     * Test the property 'totalParticipants'
     */
    @Test
    public void totalParticipantsTest() {
        // TODO: test totalParticipants
    }

    /**
     * Test the property 'totalAgents'
     */
    @Test
    public void totalAgentsTest() {
        // TODO: test totalAgents
    }

    /**
     * Test the property 'totalClients'
     */
    @Test
    public void totalClientsTest() {
        // TODO: test totalClients
    }

    /**
     * Test the property 'totalBots'
     */
    @Test
    public void totalBotsTest() {
        // TODO: test totalBots
    }

    /**
     * Test the property 'totalUnknown'
     */
    @Test
    public void totalUnknownTest() {
        // TODO: test totalUnknown
    }

    /**
     * Test the property 'clientRiskAlertsCount'
     */
    @Test
    public void clientRiskAlertsCountTest() {
        // TODO: test clientRiskAlertsCount
    }

    /**
     * Test the property 'clientBehaviorAlertsCount'
     */
    @Test
    public void clientBehaviorAlertsCountTest() {
        // TODO: test clientBehaviorAlertsCount
    }

}
