/*
 * FalaAI API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.21.49
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.falaai.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.math.BigDecimal;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for AudioInputMeta
 */
public class AudioInputMetaTest {
    private final AudioInputMeta model = new AudioInputMeta();

    /**
     * Model tests for AudioInputMeta
     */
    @Test
    public void testAudioInputMeta() {
        // TODO: test AudioInputMeta
    }

    /**
     * Test the property 'durationS'
     */
    @Test
    public void durationSTest() {
        // TODO: test durationS
    }

    /**
     * Test the property 'originalFormat'
     */
    @Test
    public void originalFormatTest() {
        // TODO: test originalFormat
    }

    /**
     * Test the property 'codec'
     */
    @Test
    public void codecTest() {
        // TODO: test codec
    }

    /**
     * Test the property 'sampleRate'
     */
    @Test
    public void sampleRateTest() {
        // TODO: test sampleRate
    }

    /**
     * Test the property 'channels'
     */
    @Test
    public void channelsTest() {
        // TODO: test channels
    }

}
