/*
 * FalaAI API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.21.49
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.falaai.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.math.BigDecimal;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for AudioEvent
 */
public class AudioEventTest {
    private final AudioEvent model = new AudioEvent();

    /**
     * Model tests for AudioEvent
     */
    @Test
    public void testAudioEvent() {
        // TODO: test AudioEvent
    }

    /**
     * Test the property 'event'
     */
    @Test
    public void eventTest() {
        // TODO: test event
    }

    /**
     * Test the property 'startS'
     */
    @Test
    public void startSTest() {
        // TODO: test startS
    }

    /**
     * Test the property 'endS'
     */
    @Test
    public void endSTest() {
        // TODO: test endS
    }

    /**
     * Test the property 'durationS'
     */
    @Test
    public void durationSTest() {
        // TODO: test durationS
    }

    /**
     * Test the property 'formattedTimestamp'
     */
    @Test
    public void formattedTimestampTest() {
        // TODO: test formattedTimestamp
    }

}
