/*
 * FalaAI API
 * Transcribe, diagnose and score calls with 3 simple endpoints.  **Endpoints:** - `POST /v1/audio/transcriptions` — Audio to text - `POST /v1/analyze/diagnostic` — Conversation analysis - `POST /v1/analyze/auditoriaRisco` — Compliance audit  **Complete flow (Python):** ```python import httpx  API = 'https://api01-falaai.action.tec.br' KEY = 'fai_xxx' HD = {'Authorization': f'Bearer {KEY}'}  # 1. Transcribe files = {'file': open('call.mp3', 'rb')} resp = httpx.post(f'{API}/v1/audio/transcriptions', headers=HD, files=files, data={'model': 'falaai-transcribe-1', 'language': 'pt'}) tr = resp.json() print(f'Text: {tr[\"text\"][:100]}...')  # 2. Diagnose resp = httpx.post(f'{API}/v1/analyze/diagnostic', headers=HD, json={'dialog': tr['dialog'], 'language': 'pt-BR', 'duration_seconds': tr['duration_seconds']}) diag = resp.json() print(f'Sentiment: {diag[\"analysis\"][\"sentiment\"][\"list_choice\"]}') print(f'Summary: {diag[\"analysis\"][\"dialogue_summary\"][\"explanation\"][:100]}...')  # 3. Audit resp = httpx.post(f'{API}/v1/analyze/auditoriaRisco', headers=HD, json={'dialogo': tr['dialog'], 'duration_seconds': tr['duration_seconds']}) audit = resp.json() print(f'Score: {audit[\"audit_score\"]} | Verdict: {audit[\"verdict\"]}') print(f'Detections: {audit[\"total_detections\"]} | Violations: {len(audit[\"violations\"])} | Positives: {len(audit[\"positives\"])}') ```  **Authentication:** All endpoints require an API Key in the `Authorization` header: `Bearer fai_xxx`  Get your API Key at [falaai.action.tec.br/api](https://falaai.action.tec.br/api)
 *
 * The version of the OpenAPI document: 1.21.47
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.falaai.model;

import com.falaai.model.AuditoriaRiscoAnalysisV2;
import com.falaai.model.AuditoriaRiscoAudioEventModelV2;
import com.falaai.model.AuditoriaRiscoAuditDecisionsV2;
import com.falaai.model.AuditoriaRiscoDetectionsV2;
import com.falaai.model.AuditoriaRiscoIndexerV2;
import com.falaai.model.AuditoriaRiscoMetaV2;
import com.falaai.model.AuditoriaRiscoParticipantsV2;
import com.falaai.model.AuditoriaRiscoScoresV2;
import com.falaai.model.AuditoriaRiscoScoringExplanationV2;
import com.falaai.model.AuditoriaRiscoSummaryV2;
import com.falaai.model.AuditoriaRiscoTimelineV2;
import com.falaai.model.AuditoriaRiscoVerdictV2;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import java.util.HashMap;
import java.util.Map;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for AuditoriaRiscoV2
 */
public class AuditoriaRiscoV2Test {
    private final AuditoriaRiscoV2 model = new AuditoriaRiscoV2();

    /**
     * Model tests for AuditoriaRiscoV2
     */
    @Test
    public void testAuditoriaRiscoV2() {
        // TODO: test AuditoriaRiscoV2
    }

    /**
     * Test the property 'meta'
     */
    @Test
    public void metaTest() {
        // TODO: test meta
    }

    /**
     * Test the property 'participants'
     */
    @Test
    public void participantsTest() {
        // TODO: test participants
    }

    /**
     * Test the property 'verdict'
     */
    @Test
    public void verdictTest() {
        // TODO: test verdict
    }

    /**
     * Test the property 'scores'
     */
    @Test
    public void scoresTest() {
        // TODO: test scores
    }

    /**
     * Test the property 'detections'
     */
    @Test
    public void detectionsTest() {
        // TODO: test detections
    }

    /**
     * Test the property 'analysis'
     */
    @Test
    public void analysisTest() {
        // TODO: test analysis
    }

    /**
     * Test the property 'timeline'
     */
    @Test
    public void timelineTest() {
        // TODO: test timeline
    }

    /**
     * Test the property 'audioEventModel'
     */
    @Test
    public void audioEventModelTest() {
        // TODO: test audioEventModel
    }

    /**
     * Test the property 'categoriesSummary'
     */
    @Test
    public void categoriesSummaryTest() {
        // TODO: test categoriesSummary
    }

    /**
     * Test the property 'indexer'
     */
    @Test
    public void indexerTest() {
        // TODO: test indexer
    }

    /**
     * Test the property 'summary'
     */
    @Test
    public void summaryTest() {
        // TODO: test summary
    }

    /**
     * Test the property 'acoesI18n'
     */
    @Test
    public void acoesI18nTest() {
        // TODO: test acoesI18n
    }

    /**
     * Test the property 'auditDecisions'
     */
    @Test
    public void auditDecisionsTest() {
        // TODO: test auditDecisions
    }

    /**
     * Test the property 'scoringExplanation'
     */
    @Test
    public void scoringExplanationTest() {
        // TODO: test scoringExplanation
    }

    /**
     * Test the property 'htmlReport'
     */
    @Test
    public void htmlReportTest() {
        // TODO: test htmlReport
    }

}
