/*
 * FalaAI API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.21.49
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.falaai.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for DiagnosticCategoricalAnalysis
 */
public class DiagnosticCategoricalAnalysisTest {
    private final DiagnosticCategoricalAnalysis model = new DiagnosticCategoricalAnalysis();

    /**
     * Model tests for DiagnosticCategoricalAnalysis
     */
    @Test
    public void testDiagnosticCategoricalAnalysis() {
        // TODO: test DiagnosticCategoricalAnalysis
    }

    /**
     * Test the property 'listChoice'
     */
    @Test
    public void listChoiceTest() {
        // TODO: test listChoice
    }

    /**
     * Test the property 'justification'
     */
    @Test
    public void justificationTest() {
        // TODO: test justification
    }

    /**
     * Test the property 'evidencePhrases'
     */
    @Test
    public void evidencePhrasesTest() {
        // TODO: test evidencePhrases
    }

}
