/*
 * FalaAI API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.21.49
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.falaai.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for DiagnosticUsage
 */
public class DiagnosticUsageTest {
    private final DiagnosticUsage model = new DiagnosticUsage();

    /**
     * Model tests for DiagnosticUsage
     */
    @Test
    public void testDiagnosticUsage() {
        // TODO: test DiagnosticUsage
    }

    /**
     * Test the property 'characters'
     */
    @Test
    public void charactersTest() {
        // TODO: test characters
    }

    /**
     * Test the property 'creditsConsumed'
     */
    @Test
    public void creditsConsumedTest() {
        // TODO: test creditsConsumed
    }

    /**
     * Test the property 'processingMs'
     */
    @Test
    public void processingMsTest() {
        // TODO: test processingMs
    }

}
