/*
 * FalaAI API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.21.49
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.falaai.model;

import com.falaai.model.DiagnosticAnalysisMap;
import com.falaai.model.DiagnosticUsage;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for DiagnosticResponse
 */
public class DiagnosticResponseTest {
    private final DiagnosticResponse model = new DiagnosticResponse();

    /**
     * Model tests for DiagnosticResponse
     */
    @Test
    public void testDiagnosticResponse() {
        // TODO: test DiagnosticResponse
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'responseLanguage'
     */
    @Test
    public void responseLanguageTest() {
        // TODO: test responseLanguage
    }

    /**
     * Test the property '_object'
     */
    @Test
    public void _objectTest() {
        // TODO: test _object
    }

    /**
     * Test the property 'analysis'
     */
    @Test
    public void analysisTest() {
        // TODO: test analysis
    }

    /**
     * Test the property 'usage'
     */
    @Test
    public void usageTest() {
        // TODO: test usage
    }

    /**
     * Test the property 'clientReferenceId'
     */
    @Test
    public void clientReferenceIdTest() {
        // TODO: test clientReferenceId
    }

}
