/*
 * FalaAI API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.21.49
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.falaai.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.openapitools.jackson.nullable.JsonNullable;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for RiskAuditSummaryV2
 */
public class RiskAuditSummaryV2Test {
    private final RiskAuditSummaryV2 model = new RiskAuditSummaryV2();

    /**
     * Model tests for RiskAuditSummaryV2
     */
    @Test
    public void testRiskAuditSummaryV2() {
        // TODO: test RiskAuditSummaryV2
    }

    /**
     * Test the property 'totalTurns'
     */
    @Test
    public void totalTurnsTest() {
        // TODO: test totalTurns
    }

    /**
     * Test the property 'totalCalibrated'
     */
    @Test
    public void totalCalibratedTest() {
        // TODO: test totalCalibrated
    }

    /**
     * Test the property 'active'
     */
    @Test
    public void activeTest() {
        // TODO: test active
    }

    /**
     * Test the property 'tolerated'
     */
    @Test
    public void toleratedTest() {
        // TODO: test tolerated
    }

    /**
     * Test the property 'blocked'
     */
    @Test
    public void blockedTest() {
        // TODO: test blocked
    }

    /**
     * Test the property 'audioEventsUsed'
     */
    @Test
    public void audioEventsUsedTest() {
        // TODO: test audioEventsUsed
    }

    /**
     * Test the property 'audioEventsAggravated'
     */
    @Test
    public void audioEventsAggravatedTest() {
        // TODO: test audioEventsAggravated
    }

    /**
     * Test the property 'macAudioApplied'
     */
    @Test
    public void macAudioAppliedTest() {
        // TODO: test macAudioApplied
    }

    /**
     * Test the property 'mvadApplied'
     */
    @Test
    public void mvadAppliedTest() {
        // TODO: test mvadApplied
    }

    /**
     * Test the property 'totalParticipants'
     */
    @Test
    public void totalParticipantsTest() {
        // TODO: test totalParticipants
    }

    /**
     * Test the property 'totalAgents'
     */
    @Test
    public void totalAgentsTest() {
        // TODO: test totalAgents
    }

    /**
     * Test the property 'totalClients'
     */
    @Test
    public void totalClientsTest() {
        // TODO: test totalClients
    }

    /**
     * Test the property 'totalBots'
     */
    @Test
    public void totalBotsTest() {
        // TODO: test totalBots
    }

    /**
     * Test the property 'totalUnknown'
     */
    @Test
    public void totalUnknownTest() {
        // TODO: test totalUnknown
    }

    /**
     * Test the property 'clientRiskAlertsCount'
     */
    @Test
    public void clientRiskAlertsCountTest() {
        // TODO: test clientRiskAlertsCount
    }

    /**
     * Test the property 'clientBehaviorAlertsCount'
     */
    @Test
    public void clientBehaviorAlertsCountTest() {
        // TODO: test clientBehaviorAlertsCount
    }

}
