/*
 * FalaAI API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.21.49
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.falaai.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for RiskAuditParticipantV2
 */
public class RiskAuditParticipantV2Test {
    private final RiskAuditParticipantV2 model = new RiskAuditParticipantV2();

    /**
     * Model tests for RiskAuditParticipantV2
     */
    @Test
    public void testRiskAuditParticipantV2() {
        // TODO: test RiskAuditParticipantV2
    }

    /**
     * Test the property 'interlocutor'
     */
    @Test
    public void interlocutorTest() {
        // TODO: test interlocutor
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'role'
     */
    @Test
    public void roleTest() {
        // TODO: test role
    }

    /**
     * Test the property 'confidence'
     */
    @Test
    public void confidenceTest() {
        // TODO: test confidence
    }

    /**
     * Test the property 'source'
     */
    @Test
    public void sourceTest() {
        // TODO: test source
    }

    /**
     * Test the property 'evidence'
     */
    @Test
    public void evidenceTest() {
        // TODO: test evidence
    }

}
