/*
 * FalaAI API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.21.49
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.falaai.model;

import com.falaai.model.RiskAuditUsageV2;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.math.BigDecimal;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for RiskAuditMetaV2
 */
public class RiskAuditMetaV2Test {
    private final RiskAuditMetaV2 model = new RiskAuditMetaV2();

    /**
     * Model tests for RiskAuditMetaV2
     */
    @Test
    public void testRiskAuditMetaV2() {
        // TODO: test RiskAuditMetaV2
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property '_object'
     */
    @Test
    public void _objectTest() {
        // TODO: test _object
    }

    /**
     * Test the property 'callDurationS'
     */
    @Test
    public void callDurationSTest() {
        // TODO: test callDurationS
    }

    /**
     * Test the property 'analyzedAt'
     */
    @Test
    public void analyzedAtTest() {
        // TODO: test analyzedAt
    }

    /**
     * Test the property 'usage'
     */
    @Test
    public void usageTest() {
        // TODO: test usage
    }

    /**
     * Test the property 'clientReferenceId'
     */
    @Test
    public void clientReferenceIdTest() {
        // TODO: test clientReferenceId
    }

}
