/*
 * FalaAI API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.21.49
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.falaai.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.util.Map;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for RiskAuditTimelineV2
 */
public class RiskAuditTimelineV2Test {
    private final RiskAuditTimelineV2 model = new RiskAuditTimelineV2();

    /**
     * Model tests for RiskAuditTimelineV2
     */
    @Test
    public void testRiskAuditTimelineV2() {
        // TODO: test RiskAuditTimelineV2
    }

    /**
     * Test the property 'turnsSentiment'
     */
    @Test
    public void turnsSentimentTest() {
        // TODO: test turnsSentiment
    }

    /**
     * Test the property 'audioEvents'
     */
    @Test
    public void audioEventsTest() {
        // TODO: test audioEvents
    }

    /**
     * Test the property 'audioGroupsFound'
     */
    @Test
    public void audioGroupsFoundTest() {
        // TODO: test audioGroupsFound
    }

}
