/*
 * FalaAI API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.21.49
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.falaai.api;

import com.falaai.ApiCallback;
import com.falaai.ApiClient;
import com.falaai.ApiException;
import com.falaai.ApiResponse;
import com.falaai.Configuration;
import com.falaai.Pair;
import com.falaai.ProgressRequestBody;
import com.falaai.ProgressResponseBody;

import com.google.gson.reflect.TypeToken;

import java.io.IOException;


import com.falaai.model.DiagnosticRequest;
import com.falaai.model.DiagnosticResponse;
import com.falaai.model.HTTPValidationError;
import com.falaai.model.RiskAuditRequest;
import com.falaai.model.RiskAuditV2Response;

import java.lang.reflect.Type;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class AnalysisApi {
    private ApiClient localVarApiClient;
    private int localHostIndex;
    private String localCustomBaseUrl;

    public AnalysisApi() {
        this(Configuration.getDefaultApiClient());
    }

    public AnalysisApi(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public ApiClient getApiClient() {
        return localVarApiClient;
    }

    public void setApiClient(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public int getHostIndex() {
        return localHostIndex;
    }

    public void setHostIndex(int hostIndex) {
        this.localHostIndex = hostIndex;
    }

    public String getCustomBaseUrl() {
        return localCustomBaseUrl;
    }

    public void setCustomBaseUrl(String customBaseUrl) {
        this.localCustomBaseUrl = customBaseUrl;
    }

    /**
     * Build call for createDiagnosticV1AnalyzeDiagnosticPost
     * @param diagnosticRequest  (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful Response </td><td>  -  </td></tr>
        <tr><td> 422 </td><td> Validation Error </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call createDiagnosticV1AnalyzeDiagnosticPostCall(@jakarta.annotation.Nonnull DiagnosticRequest diagnosticRequest, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = diagnosticRequest;

        // create path and map variables
        String localVarPath = "/v1/analyze/diagnostic";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
            "application/json"
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "ApiKeyAuth" };
        return localVarApiClient.buildCall(basePath, localVarPath, "POST", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call createDiagnosticV1AnalyzeDiagnosticPostValidateBeforeCall(@jakarta.annotation.Nonnull DiagnosticRequest diagnosticRequest, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'diagnosticRequest' is set
        if (diagnosticRequest == null) {
            throw new ApiException("Missing the required parameter 'diagnosticRequest' when calling createDiagnosticV1AnalyzeDiagnosticPost(Async)");
        }

        return createDiagnosticV1AnalyzeDiagnosticPostCall(diagnosticRequest, _callback);

    }

    /**
     * Analyze a call transcript — 5 parallel analyses
     * 
     * @param diagnosticRequest  (required)
     * @return DiagnosticResponse
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful Response </td><td>  -  </td></tr>
        <tr><td> 422 </td><td> Validation Error </td><td>  -  </td></tr>
     </table>
     */
    public DiagnosticResponse createDiagnosticV1AnalyzeDiagnosticPost(@jakarta.annotation.Nonnull DiagnosticRequest diagnosticRequest) throws ApiException {
        ApiResponse<DiagnosticResponse> localVarResp = createDiagnosticV1AnalyzeDiagnosticPostWithHttpInfo(diagnosticRequest);
        return localVarResp.getData();
    }

    /**
     * Analyze a call transcript — 5 parallel analyses
     * 
     * @param diagnosticRequest  (required)
     * @return ApiResponse&lt;DiagnosticResponse&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful Response </td><td>  -  </td></tr>
        <tr><td> 422 </td><td> Validation Error </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<DiagnosticResponse> createDiagnosticV1AnalyzeDiagnosticPostWithHttpInfo(@jakarta.annotation.Nonnull DiagnosticRequest diagnosticRequest) throws ApiException {
        okhttp3.Call localVarCall = createDiagnosticV1AnalyzeDiagnosticPostValidateBeforeCall(diagnosticRequest, null);
        Type localVarReturnType = new TypeToken<DiagnosticResponse>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Analyze a call transcript — 5 parallel analyses (asynchronously)
     * 
     * @param diagnosticRequest  (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful Response </td><td>  -  </td></tr>
        <tr><td> 422 </td><td> Validation Error </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call createDiagnosticV1AnalyzeDiagnosticPostAsync(@jakarta.annotation.Nonnull DiagnosticRequest diagnosticRequest, final ApiCallback<DiagnosticResponse> _callback) throws ApiException {

        okhttp3.Call localVarCall = createDiagnosticV1AnalyzeDiagnosticPostValidateBeforeCall(diagnosticRequest, _callback);
        Type localVarReturnType = new TypeToken<DiagnosticResponse>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for createRiskAuditV1AnalyzeRiskAuditPost
     * @param riskAuditRequest  (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful Response </td><td>  -  </td></tr>
        <tr><td> 422 </td><td> Validation Error </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call createRiskAuditV1AnalyzeRiskAuditPostCall(@jakarta.annotation.Nonnull RiskAuditRequest riskAuditRequest, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = riskAuditRequest;

        // create path and map variables
        String localVarPath = "/v1/analyze/riskAudit";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
            "application/json"
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "ApiKeyAuth" };
        return localVarApiClient.buildCall(basePath, localVarPath, "POST", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call createRiskAuditV1AnalyzeRiskAuditPostValidateBeforeCall(@jakarta.annotation.Nonnull RiskAuditRequest riskAuditRequest, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'riskAuditRequest' is set
        if (riskAuditRequest == null) {
            throw new ApiException("Missing the required parameter 'riskAuditRequest' when calling createRiskAuditV1AnalyzeRiskAuditPost(Async)");
        }

        return createRiskAuditV1AnalyzeRiskAuditPostCall(riskAuditRequest, _callback);

    }

    /**
     * Compliance Risk Audit — conversation compliance analysis
     * 
     * @param riskAuditRequest  (required)
     * @return RiskAuditV2Response
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful Response </td><td>  -  </td></tr>
        <tr><td> 422 </td><td> Validation Error </td><td>  -  </td></tr>
     </table>
     */
    public RiskAuditV2Response createRiskAuditV1AnalyzeRiskAuditPost(@jakarta.annotation.Nonnull RiskAuditRequest riskAuditRequest) throws ApiException {
        ApiResponse<RiskAuditV2Response> localVarResp = createRiskAuditV1AnalyzeRiskAuditPostWithHttpInfo(riskAuditRequest);
        return localVarResp.getData();
    }

    /**
     * Compliance Risk Audit — conversation compliance analysis
     * 
     * @param riskAuditRequest  (required)
     * @return ApiResponse&lt;RiskAuditV2Response&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful Response </td><td>  -  </td></tr>
        <tr><td> 422 </td><td> Validation Error </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<RiskAuditV2Response> createRiskAuditV1AnalyzeRiskAuditPostWithHttpInfo(@jakarta.annotation.Nonnull RiskAuditRequest riskAuditRequest) throws ApiException {
        okhttp3.Call localVarCall = createRiskAuditV1AnalyzeRiskAuditPostValidateBeforeCall(riskAuditRequest, null);
        Type localVarReturnType = new TypeToken<RiskAuditV2Response>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Compliance Risk Audit — conversation compliance analysis (asynchronously)
     * 
     * @param riskAuditRequest  (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful Response </td><td>  -  </td></tr>
        <tr><td> 422 </td><td> Validation Error </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call createRiskAuditV1AnalyzeRiskAuditPostAsync(@jakarta.annotation.Nonnull RiskAuditRequest riskAuditRequest, final ApiCallback<RiskAuditV2Response> _callback) throws ApiException {

        okhttp3.Call localVarCall = createRiskAuditV1AnalyzeRiskAuditPostValidateBeforeCall(riskAuditRequest, _callback);
        Type localVarReturnType = new TypeToken<RiskAuditV2Response>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
}
