/*
 * FalaAI API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.21.49
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.falaai.api;

import com.falaai.ApiCallback;
import com.falaai.ApiClient;
import com.falaai.ApiException;
import com.falaai.ApiResponse;
import com.falaai.Configuration;
import com.falaai.Pair;
import com.falaai.ProgressRequestBody;
import com.falaai.ProgressResponseBody;

import com.google.gson.reflect.TypeToken;

import java.io.IOException;


import java.io.File;
import com.falaai.model.HTTPValidationError;
import com.falaai.model.TranscriptionResponse;

import java.lang.reflect.Type;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class SpeechApi {
    private ApiClient localVarApiClient;
    private int localHostIndex;
    private String localCustomBaseUrl;

    public SpeechApi() {
        this(Configuration.getDefaultApiClient());
    }

    public SpeechApi(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public ApiClient getApiClient() {
        return localVarApiClient;
    }

    public void setApiClient(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public int getHostIndex() {
        return localHostIndex;
    }

    public void setHostIndex(int hostIndex) {
        this.localHostIndex = hostIndex;
    }

    public String getCustomBaseUrl() {
        return localCustomBaseUrl;
    }

    public void setCustomBaseUrl(String customBaseUrl) {
        this.localCustomBaseUrl = customBaseUrl;
    }

    /**
     * Build call for createTranscriptionV1AudioTranscriptionsPost
     * @param _file  (required)
     * @param model  (optional, default to falaai-transcribe-1)
     * @param language  (optional, default to pt)
     * @param clientReferenceId Optional client-supplied ID echoed verbatim in the response. Use to correlate/sync with your system. Accepted charset: [A-Za-z0-9._:-]. Not idempotency. (optional)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful Response </td><td>  -  </td></tr>
        <tr><td> 422 </td><td> Validation Error </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call createTranscriptionV1AudioTranscriptionsPostCall(@jakarta.annotation.Nonnull File _file, @jakarta.annotation.Nullable String model, @jakarta.annotation.Nullable String language, @jakarta.annotation.Nullable String clientReferenceId, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/v1/audio/transcriptions";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        if (_file != null) {
            localVarFormParams.put("file", _file);
        }

        if (model != null) {
            localVarFormParams.put("model", model);
        }

        if (language != null) {
            localVarFormParams.put("language", language);
        }

        if (clientReferenceId != null) {
            localVarFormParams.put("client_reference_id", clientReferenceId);
        }

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
            "multipart/form-data"
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "ApiKeyAuth" };
        return localVarApiClient.buildCall(basePath, localVarPath, "POST", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call createTranscriptionV1AudioTranscriptionsPostValidateBeforeCall(@jakarta.annotation.Nonnull File _file, @jakarta.annotation.Nullable String model, @jakarta.annotation.Nullable String language, @jakarta.annotation.Nullable String clientReferenceId, final ApiCallback _callback) throws ApiException {
        // verify the required parameter '_file' is set
        if (_file == null) {
            throw new ApiException("Missing the required parameter '_file' when calling createTranscriptionV1AudioTranscriptionsPost(Async)");
        }

        return createTranscriptionV1AudioTranscriptionsPostCall(_file, model, language, clientReferenceId, _callback);

    }

    /**
     * Transcribe audio to text
     * 
     * @param _file  (required)
     * @param model  (optional, default to falaai-transcribe-1)
     * @param language  (optional, default to pt)
     * @param clientReferenceId Optional client-supplied ID echoed verbatim in the response. Use to correlate/sync with your system. Accepted charset: [A-Za-z0-9._:-]. Not idempotency. (optional)
     * @return TranscriptionResponse
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful Response </td><td>  -  </td></tr>
        <tr><td> 422 </td><td> Validation Error </td><td>  -  </td></tr>
     </table>
     */
    public TranscriptionResponse createTranscriptionV1AudioTranscriptionsPost(@jakarta.annotation.Nonnull File _file, @jakarta.annotation.Nullable String model, @jakarta.annotation.Nullable String language, @jakarta.annotation.Nullable String clientReferenceId) throws ApiException {
        ApiResponse<TranscriptionResponse> localVarResp = createTranscriptionV1AudioTranscriptionsPostWithHttpInfo(_file, model, language, clientReferenceId);
        return localVarResp.getData();
    }

    /**
     * Transcribe audio to text
     * 
     * @param _file  (required)
     * @param model  (optional, default to falaai-transcribe-1)
     * @param language  (optional, default to pt)
     * @param clientReferenceId Optional client-supplied ID echoed verbatim in the response. Use to correlate/sync with your system. Accepted charset: [A-Za-z0-9._:-]. Not idempotency. (optional)
     * @return ApiResponse&lt;TranscriptionResponse&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful Response </td><td>  -  </td></tr>
        <tr><td> 422 </td><td> Validation Error </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<TranscriptionResponse> createTranscriptionV1AudioTranscriptionsPostWithHttpInfo(@jakarta.annotation.Nonnull File _file, @jakarta.annotation.Nullable String model, @jakarta.annotation.Nullable String language, @jakarta.annotation.Nullable String clientReferenceId) throws ApiException {
        okhttp3.Call localVarCall = createTranscriptionV1AudioTranscriptionsPostValidateBeforeCall(_file, model, language, clientReferenceId, null);
        Type localVarReturnType = new TypeToken<TranscriptionResponse>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Transcribe audio to text (asynchronously)
     * 
     * @param _file  (required)
     * @param model  (optional, default to falaai-transcribe-1)
     * @param language  (optional, default to pt)
     * @param clientReferenceId Optional client-supplied ID echoed verbatim in the response. Use to correlate/sync with your system. Accepted charset: [A-Za-z0-9._:-]. Not idempotency. (optional)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful Response </td><td>  -  </td></tr>
        <tr><td> 422 </td><td> Validation Error </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call createTranscriptionV1AudioTranscriptionsPostAsync(@jakarta.annotation.Nonnull File _file, @jakarta.annotation.Nullable String model, @jakarta.annotation.Nullable String language, @jakarta.annotation.Nullable String clientReferenceId, final ApiCallback<TranscriptionResponse> _callback) throws ApiException {

        okhttp3.Call localVarCall = createTranscriptionV1AudioTranscriptionsPostValidateBeforeCall(_file, model, language, clientReferenceId, _callback);
        Type localVarReturnType = new TypeToken<TranscriptionResponse>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
}
